// EntDB Console — curated, browser-facing API.
//
// This proto file is the LITERAL access policy for the entdb-console binary.
// Every RPC the browser is allowed to call MUST be declared here. Anything
// not listed is unreachable from the SPA — the ConnectRPC handler has no
// route for it, full stop. This is intentional: the proto is the security
// boundary, not a stylistic choice.
//
// Each RPC reuses the request/response messages from the upstream
// `entdb.v1.EntDBService` proto so each Console handler is a one-line
// pass-through to the upstream gRPC client. Adding a new RPC therefore
// requires touching this file (and getting it through review) rather
// than just exposing whatever the upstream happens to support.
//
// Scope (PR 2): read-only RPCs from PR 1, plus narrow sandbox-only
// CREATE write RPCs (`SandboxCreateNode`, `SandboxCreateEdge`). Writes
// are gated to a single configured sandbox tenant; the console binary
// rejects any other tenant id at the handler. The sandbox RPCs use
// narrow request/response messages defined in this file (NOT
// `entdb.v1.ExecuteAtomicRequest`) so the browser can never construct
// a multi-op transaction or target arbitrary fields outside the
// curated CREATE shape. The handler builds the underlying single-op
// `ExecuteAtomicRequest` itself before forwarding upstream.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: console.proto

package consolev1

import (
	context "context"
	pb "github.com/elloloop/tenant-shard-db/server/go/internal/pb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Console_Health_FullMethodName            = "/entdb.console.v1.Console/Health"
	Console_ListTenants_FullMethodName       = "/entdb.console.v1.Console/ListTenants"
	Console_GetTenant_FullMethodName         = "/entdb.console.v1.Console/GetTenant"
	Console_GetSchema_FullMethodName         = "/entdb.console.v1.Console/GetSchema"
	Console_QueryNodes_FullMethodName        = "/entdb.console.v1.Console/QueryNodes"
	Console_GetNode_FullMethodName           = "/entdb.console.v1.Console/GetNode"
	Console_GetEdgesFrom_FullMethodName      = "/entdb.console.v1.Console/GetEdgesFrom"
	Console_GetEdgesTo_FullMethodName        = "/entdb.console.v1.Console/GetEdgesTo"
	Console_GetConnectedNodes_FullMethodName = "/entdb.console.v1.Console/GetConnectedNodes"
	Console_SearchMailbox_FullMethodName     = "/entdb.console.v1.Console/SearchMailbox"
	Console_SandboxCreateNode_FullMethodName = "/entdb.console.v1.Console/SandboxCreateNode"
	Console_SandboxCreateEdge_FullMethodName = "/entdb.console.v1.Console/SandboxCreateEdge"
)

// ConsoleClient is the client API for Console service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Console — curated read-only surface for the EntDB web console.
//
// All RPCs forward to the upstream `entdb.v1.EntDBService` after the
// console binary attaches the configured API key as a Bearer token on
// the outgoing gRPC metadata. The console NEVER calls upstream RPCs
// not listed here.
type ConsoleClient interface {
	// Liveness/readiness probe for the console binary itself. Forwards to
	// upstream Health so the response also reflects upstream availability.
	Health(ctx context.Context, in *pb.HealthRequest, opts ...grpc.CallOption) (*pb.HealthResponse, error)
	// List tenants the configured caller can see.
	ListTenants(ctx context.Context, in *pb.ListTenantsRequest, opts ...grpc.CallOption) (*pb.ListTenantsResponse, error)
	// Get a tenant by id.
	GetTenant(ctx context.Context, in *pb.GetTenantRequest, opts ...grpc.CallOption) (*pb.GetTenantResponse, error)
	// Get the active schema (optionally for a specific type).
	GetSchema(ctx context.Context, in *pb.GetSchemaRequest, opts ...grpc.CallOption) (*pb.GetSchemaResponse, error)
	// Query nodes by type with typed filters + pagination.
	QueryNodes(ctx context.Context, in *pb.QueryNodesRequest, opts ...grpc.CallOption) (*pb.QueryNodesResponse, error)
	// Get a single node by id.
	GetNode(ctx context.Context, in *pb.GetNodeRequest, opts ...grpc.CallOption) (*pb.GetNodeResponse, error)
	// Outgoing edges from a node.
	GetEdgesFrom(ctx context.Context, in *pb.GetEdgesRequest, opts ...grpc.CallOption) (*pb.GetEdgesResponse, error)
	// Incoming edges to a node.
	GetEdgesTo(ctx context.Context, in *pb.GetEdgesRequest, opts ...grpc.CallOption) (*pb.GetEdgesResponse, error)
	// Connected nodes (ACL-filtered) for a graph view.
	GetConnectedNodes(ctx context.Context, in *pb.GetConnectedNodesRequest, opts ...grpc.CallOption) (*pb.GetConnectedNodesResponse, error)
	// Search a user mailbox.
	SearchMailbox(ctx context.Context, in *pb.SearchMailboxRequest, opts ...grpc.CallOption) (*pb.SearchMailboxResponse, error)
	// Create a single node in the configured sandbox tenant.
	//
	// The handler:
	//  1. Rejects with `unimplemented` if no sandbox tenant is configured.
	//  2. Rejects with `permission_denied` if `tenant_id` does not match
	//     the configured sandbox tenant.
	//  3. Builds a single-op `entdb.v1.ExecuteAtomicRequest` with
	//     `wait_applied = true` so success means the write is applied,
	//     not just queued.
	SandboxCreateNode(ctx context.Context, in *SandboxCreateNodeRequest, opts ...grpc.CallOption) (*SandboxCreateNodeResponse, error)
	// Create a single edge in the configured sandbox tenant. Same gating
	// semantics as `SandboxCreateNode`.
	SandboxCreateEdge(ctx context.Context, in *SandboxCreateEdgeRequest, opts ...grpc.CallOption) (*SandboxCreateEdgeResponse, error)
}

type consoleClient struct {
	cc grpc.ClientConnInterface
}

func NewConsoleClient(cc grpc.ClientConnInterface) ConsoleClient {
	return &consoleClient{cc}
}

func (c *consoleClient) Health(ctx context.Context, in *pb.HealthRequest, opts ...grpc.CallOption) (*pb.HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.HealthResponse)
	err := c.cc.Invoke(ctx, Console_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleClient) ListTenants(ctx context.Context, in *pb.ListTenantsRequest, opts ...grpc.CallOption) (*pb.ListTenantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.ListTenantsResponse)
	err := c.cc.Invoke(ctx, Console_ListTenants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleClient) GetTenant(ctx context.Context, in *pb.GetTenantRequest, opts ...grpc.CallOption) (*pb.GetTenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.GetTenantResponse)
	err := c.cc.Invoke(ctx, Console_GetTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleClient) GetSchema(ctx context.Context, in *pb.GetSchemaRequest, opts ...grpc.CallOption) (*pb.GetSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.GetSchemaResponse)
	err := c.cc.Invoke(ctx, Console_GetSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleClient) QueryNodes(ctx context.Context, in *pb.QueryNodesRequest, opts ...grpc.CallOption) (*pb.QueryNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.QueryNodesResponse)
	err := c.cc.Invoke(ctx, Console_QueryNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleClient) GetNode(ctx context.Context, in *pb.GetNodeRequest, opts ...grpc.CallOption) (*pb.GetNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.GetNodeResponse)
	err := c.cc.Invoke(ctx, Console_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleClient) GetEdgesFrom(ctx context.Context, in *pb.GetEdgesRequest, opts ...grpc.CallOption) (*pb.GetEdgesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.GetEdgesResponse)
	err := c.cc.Invoke(ctx, Console_GetEdgesFrom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleClient) GetEdgesTo(ctx context.Context, in *pb.GetEdgesRequest, opts ...grpc.CallOption) (*pb.GetEdgesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.GetEdgesResponse)
	err := c.cc.Invoke(ctx, Console_GetEdgesTo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleClient) GetConnectedNodes(ctx context.Context, in *pb.GetConnectedNodesRequest, opts ...grpc.CallOption) (*pb.GetConnectedNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.GetConnectedNodesResponse)
	err := c.cc.Invoke(ctx, Console_GetConnectedNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleClient) SearchMailbox(ctx context.Context, in *pb.SearchMailboxRequest, opts ...grpc.CallOption) (*pb.SearchMailboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.SearchMailboxResponse)
	err := c.cc.Invoke(ctx, Console_SearchMailbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleClient) SandboxCreateNode(ctx context.Context, in *SandboxCreateNodeRequest, opts ...grpc.CallOption) (*SandboxCreateNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxCreateNodeResponse)
	err := c.cc.Invoke(ctx, Console_SandboxCreateNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleClient) SandboxCreateEdge(ctx context.Context, in *SandboxCreateEdgeRequest, opts ...grpc.CallOption) (*SandboxCreateEdgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxCreateEdgeResponse)
	err := c.cc.Invoke(ctx, Console_SandboxCreateEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsoleServer is the server API for Console service.
// All implementations must embed UnimplementedConsoleServer
// for forward compatibility.
//
// Console — curated read-only surface for the EntDB web console.
//
// All RPCs forward to the upstream `entdb.v1.EntDBService` after the
// console binary attaches the configured API key as a Bearer token on
// the outgoing gRPC metadata. The console NEVER calls upstream RPCs
// not listed here.
type ConsoleServer interface {
	// Liveness/readiness probe for the console binary itself. Forwards to
	// upstream Health so the response also reflects upstream availability.
	Health(context.Context, *pb.HealthRequest) (*pb.HealthResponse, error)
	// List tenants the configured caller can see.
	ListTenants(context.Context, *pb.ListTenantsRequest) (*pb.ListTenantsResponse, error)
	// Get a tenant by id.
	GetTenant(context.Context, *pb.GetTenantRequest) (*pb.GetTenantResponse, error)
	// Get the active schema (optionally for a specific type).
	GetSchema(context.Context, *pb.GetSchemaRequest) (*pb.GetSchemaResponse, error)
	// Query nodes by type with typed filters + pagination.
	QueryNodes(context.Context, *pb.QueryNodesRequest) (*pb.QueryNodesResponse, error)
	// Get a single node by id.
	GetNode(context.Context, *pb.GetNodeRequest) (*pb.GetNodeResponse, error)
	// Outgoing edges from a node.
	GetEdgesFrom(context.Context, *pb.GetEdgesRequest) (*pb.GetEdgesResponse, error)
	// Incoming edges to a node.
	GetEdgesTo(context.Context, *pb.GetEdgesRequest) (*pb.GetEdgesResponse, error)
	// Connected nodes (ACL-filtered) for a graph view.
	GetConnectedNodes(context.Context, *pb.GetConnectedNodesRequest) (*pb.GetConnectedNodesResponse, error)
	// Search a user mailbox.
	SearchMailbox(context.Context, *pb.SearchMailboxRequest) (*pb.SearchMailboxResponse, error)
	// Create a single node in the configured sandbox tenant.
	//
	// The handler:
	//  1. Rejects with `unimplemented` if no sandbox tenant is configured.
	//  2. Rejects with `permission_denied` if `tenant_id` does not match
	//     the configured sandbox tenant.
	//  3. Builds a single-op `entdb.v1.ExecuteAtomicRequest` with
	//     `wait_applied = true` so success means the write is applied,
	//     not just queued.
	SandboxCreateNode(context.Context, *SandboxCreateNodeRequest) (*SandboxCreateNodeResponse, error)
	// Create a single edge in the configured sandbox tenant. Same gating
	// semantics as `SandboxCreateNode`.
	SandboxCreateEdge(context.Context, *SandboxCreateEdgeRequest) (*SandboxCreateEdgeResponse, error)
	mustEmbedUnimplementedConsoleServer()
}

// UnimplementedConsoleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConsoleServer struct{}

func (UnimplementedConsoleServer) Health(context.Context, *pb.HealthRequest) (*pb.HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedConsoleServer) ListTenants(context.Context, *pb.ListTenantsRequest) (*pb.ListTenantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTenants not implemented")
}
func (UnimplementedConsoleServer) GetTenant(context.Context, *pb.GetTenantRequest) (*pb.GetTenantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTenant not implemented")
}
func (UnimplementedConsoleServer) GetSchema(context.Context, *pb.GetSchemaRequest) (*pb.GetSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSchema not implemented")
}
func (UnimplementedConsoleServer) QueryNodes(context.Context, *pb.QueryNodesRequest) (*pb.QueryNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryNodes not implemented")
}
func (UnimplementedConsoleServer) GetNode(context.Context, *pb.GetNodeRequest) (*pb.GetNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedConsoleServer) GetEdgesFrom(context.Context, *pb.GetEdgesRequest) (*pb.GetEdgesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEdgesFrom not implemented")
}
func (UnimplementedConsoleServer) GetEdgesTo(context.Context, *pb.GetEdgesRequest) (*pb.GetEdgesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEdgesTo not implemented")
}
func (UnimplementedConsoleServer) GetConnectedNodes(context.Context, *pb.GetConnectedNodesRequest) (*pb.GetConnectedNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConnectedNodes not implemented")
}
func (UnimplementedConsoleServer) SearchMailbox(context.Context, *pb.SearchMailboxRequest) (*pb.SearchMailboxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchMailbox not implemented")
}
func (UnimplementedConsoleServer) SandboxCreateNode(context.Context, *SandboxCreateNodeRequest) (*SandboxCreateNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SandboxCreateNode not implemented")
}
func (UnimplementedConsoleServer) SandboxCreateEdge(context.Context, *SandboxCreateEdgeRequest) (*SandboxCreateEdgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SandboxCreateEdge not implemented")
}
func (UnimplementedConsoleServer) mustEmbedUnimplementedConsoleServer() {}
func (UnimplementedConsoleServer) testEmbeddedByValue()                 {}

// UnsafeConsoleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsoleServer will
// result in compilation errors.
type UnsafeConsoleServer interface {
	mustEmbedUnimplementedConsoleServer()
}

func RegisterConsoleServer(s grpc.ServiceRegistrar, srv ConsoleServer) {
	// If the following call pancis, it indicates UnimplementedConsoleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Console_ServiceDesc, srv)
}

func _Console_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Console_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServer).Health(ctx, req.(*pb.HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Console_ListTenants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.ListTenantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServer).ListTenants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Console_ListTenants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServer).ListTenants(ctx, req.(*pb.ListTenantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Console_GetTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.GetTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServer).GetTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Console_GetTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServer).GetTenant(ctx, req.(*pb.GetTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Console_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.GetSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Console_GetSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServer).GetSchema(ctx, req.(*pb.GetSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Console_QueryNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.QueryNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServer).QueryNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Console_QueryNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServer).QueryNodes(ctx, req.(*pb.QueryNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Console_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Console_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServer).GetNode(ctx, req.(*pb.GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Console_GetEdgesFrom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.GetEdgesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServer).GetEdgesFrom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Console_GetEdgesFrom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServer).GetEdgesFrom(ctx, req.(*pb.GetEdgesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Console_GetEdgesTo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.GetEdgesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServer).GetEdgesTo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Console_GetEdgesTo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServer).GetEdgesTo(ctx, req.(*pb.GetEdgesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Console_GetConnectedNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.GetConnectedNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServer).GetConnectedNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Console_GetConnectedNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServer).GetConnectedNodes(ctx, req.(*pb.GetConnectedNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Console_SearchMailbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.SearchMailboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServer).SearchMailbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Console_SearchMailbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServer).SearchMailbox(ctx, req.(*pb.SearchMailboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Console_SandboxCreateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxCreateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServer).SandboxCreateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Console_SandboxCreateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServer).SandboxCreateNode(ctx, req.(*SandboxCreateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Console_SandboxCreateEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxCreateEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleServer).SandboxCreateEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Console_SandboxCreateEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleServer).SandboxCreateEdge(ctx, req.(*SandboxCreateEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Console_ServiceDesc is the grpc.ServiceDesc for Console service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Console_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "entdb.console.v1.Console",
	HandlerType: (*ConsoleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _Console_Health_Handler,
		},
		{
			MethodName: "ListTenants",
			Handler:    _Console_ListTenants_Handler,
		},
		{
			MethodName: "GetTenant",
			Handler:    _Console_GetTenant_Handler,
		},
		{
			MethodName: "GetSchema",
			Handler:    _Console_GetSchema_Handler,
		},
		{
			MethodName: "QueryNodes",
			Handler:    _Console_QueryNodes_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _Console_GetNode_Handler,
		},
		{
			MethodName: "GetEdgesFrom",
			Handler:    _Console_GetEdgesFrom_Handler,
		},
		{
			MethodName: "GetEdgesTo",
			Handler:    _Console_GetEdgesTo_Handler,
		},
		{
			MethodName: "GetConnectedNodes",
			Handler:    _Console_GetConnectedNodes_Handler,
		},
		{
			MethodName: "SearchMailbox",
			Handler:    _Console_SearchMailbox_Handler,
		},
		{
			MethodName: "SandboxCreateNode",
			Handler:    _Console_SandboxCreateNode_Handler,
		},
		{
			MethodName: "SandboxCreateEdge",
			Handler:    _Console_SandboxCreateEdge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "console.proto",
}
