package store

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"strings"

	"github.com/elloloop/tenant-shard-db/server/go/internal/schema"
)

// Node is the in-Go representation of one row of the `nodes` table.
// Field-id-keyed payload JSON is exposed verbatim — translation to
// proto Node (with Field-name-keyed fields) is the payload package's
// job, not this one (CLAUDE.md invariant #6).
type Node struct {
	TenantID    string
	NodeID      string
	TypeID      int32
	PayloadJSON string // raw JSON, keyed by field_id
	CreatedAt   int64  // unix ms
	UpdatedAt   int64  // unix ms
	OwnerActor  string
	ACLJSON     string // raw JSON list of {principal, permission} entries
}

// NodeInput is the input shape of CreateNodeRaw. The payload map must
// already be field-id-keyed (string keys for JSON marshalling, e.g.
// {"1": "alice"}).
type NodeInput struct {
	NodeID      string         // optional — generated by caller (e.g. UUID)
	TypeID      int32          // required
	Payload     map[string]any // field-id-keyed
	OwnerActor  string         // required
	ACL         []ACLEntry     // optional, default []
	CreatedAt   int64          // optional, defaults to now()
}

// ACLEntry mirrors the per-node `acl_blob` JSON shape ({principal,
// permission}). Stored verbatim alongside the node row; full ACL
// evaluation lives in the acl package.
type ACLEntry struct {
	Principal  string `json:"principal"`
	Permission string `json:"permission"`
}

// GetNode fetches one node by (tenant, node_id). Returns ErrNodeNotFound
// (NotFound) when missing.
func (s *CanonicalStore) GetNode(ctx context.Context, tenantID, nodeID string) (*Node, error) {
	db, err := s.db(tenantID)
	if err != nil {
		return nil, err
	}
	row := db.QueryRowContext(ctx, `
		SELECT tenant_id, node_id, type_id, payload_json,
		       created_at, updated_at, owner_actor, acl_blob
		FROM nodes WHERE tenant_id = ? AND node_id = ?`,
		tenantID, nodeID,
	)
	n := &Node{}
	err = row.Scan(&n.TenantID, &n.NodeID, &n.TypeID, &n.PayloadJSON,
		&n.CreatedAt, &n.UpdatedAt, &n.OwnerActor, &n.ACLJSON)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, fmt.Errorf("%w: %s/%s", ErrNodeNotFound, tenantID, nodeID)
	}
	if err != nil {
		return nil, fmt.Errorf("store: GetNode: %w", err)
	}
	return n, nil
}

// GetNodeByKey resolves a node via its declared unique field. Mirrors
// canonical_store.py:_sync_get_node_by_key (2177). Returns (nil, nil)
// when no row matches the (tenant, type, field, value) tuple — the
// miss is signalled in-band so the caller can decide between
// PERMISSION_DENIED, NOT_FOUND, or in-band found=false (the
// GetNodeByKey RPC chooses found=false; see
// docs/go-port/rpcs/GetNodeByKey.md).
//
// The lookup is byte-exact: SQLite TEXT comparison is case-sensitive
// without an explicit COLLATE NOCASE, and we add none. Callers (SDKs)
// own client-side normalisation (lowercased email, trimmed
// whitespace) per docs/decisions/unique_keys.md:90-92.
//
// The query reaches for the partial unique expression index lazily
// created by EnsureUniqueIndex. This method does NOT call
// EnsureUniqueIndex itself — the index must already exist (the
// applier creates it on the write path). Without the index the
// SELECT still works but degrades to a scan.
func (s *CanonicalStore) GetNodeByKey(ctx context.Context, tenantID string, typeID, fieldID int32, value any) (*Node, error) {
	db, err := s.db(tenantID)
	if err != nil {
		return nil, err
	}
	q := fmt.Sprintf(`
		SELECT tenant_id, node_id, type_id, payload_json,
		       created_at, updated_at, owner_actor, acl_blob
		FROM nodes
		WHERE tenant_id = ? AND type_id = ?
		  AND json_extract(payload_json, '$."%d"') = ?
		LIMIT 1`, fieldID)
	row := db.QueryRowContext(ctx, q, tenantID, typeID, value)
	n := &Node{}
	err = row.Scan(&n.TenantID, &n.NodeID, &n.TypeID, &n.PayloadJSON,
		&n.CreatedAt, &n.UpdatedAt, &n.OwnerActor, &n.ACLJSON)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("store: GetNodeByKey: %w", err)
	}
	return n, nil
}

// GetNodeByCompositeKey resolves a node via a multi-field composite
// unique tuple. Mirrors canonical_store.py:_sync_get_node_by_composite_key
// (2229). Same byte-exact contract as GetNodeByKey. Returns
// (nil, nil) on miss; (nil, error) only on infra failure.
//
// fieldIDs and values must be the same non-zero length; an empty or
// length-mismatched input returns (nil, errs.ErrInvalidArgument).
func (s *CanonicalStore) GetNodeByCompositeKey(ctx context.Context, tenantID string, typeID int32, fieldIDs []int32, values []any) (*Node, error) {
	if len(fieldIDs) == 0 || len(fieldIDs) != len(values) {
		return nil, fmt.Errorf("store: GetNodeByCompositeKey: field_ids/values length mismatch (%d vs %d)", len(fieldIDs), len(values))
	}
	db, err := s.db(tenantID)
	if err != nil {
		return nil, err
	}
	clauses := make([]string, 0, len(fieldIDs))
	for _, fid := range fieldIDs {
		clauses = append(clauses, fmt.Sprintf(`json_extract(payload_json, '$."%d"') = ?`, fid))
	}
	args := make([]any, 0, 2+len(values))
	args = append(args, tenantID, typeID)
	args = append(args, values...)
	q := fmt.Sprintf(`
		SELECT tenant_id, node_id, type_id, payload_json,
		       created_at, updated_at, owner_actor, acl_blob
		FROM nodes
		WHERE tenant_id = ? AND type_id = ?
		  AND %s
		LIMIT 1`, strings.Join(clauses, " AND "))
	row := db.QueryRowContext(ctx, q, args...)
	n := &Node{}
	err = row.Scan(&n.TenantID, &n.NodeID, &n.TypeID, &n.PayloadJSON,
		&n.CreatedAt, &n.UpdatedAt, &n.OwnerActor, &n.ACLJSON)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("store: GetNodeByCompositeKey: %w", err)
	}
	return n, nil
}

// GetNodes batch-fetches nodes by id. Returns the nodes that exist plus
// the list of missing ids (for caller-side NotFound reporting). Order
// of returned nodes is unspecified.
func (s *CanonicalStore) GetNodes(ctx context.Context, tenantID string, nodeIDs []string) (nodes []*Node, missing []string, err error) {
	if len(nodeIDs) == 0 {
		return nil, nil, nil
	}
	db, err := s.db(tenantID)
	if err != nil {
		return nil, nil, err
	}
	placeholders := strings.Repeat("?,", len(nodeIDs))
	placeholders = placeholders[:len(placeholders)-1]
	args := make([]any, 0, len(nodeIDs)+1)
	args = append(args, tenantID)
	for _, id := range nodeIDs {
		args = append(args, id)
	}
	q := fmt.Sprintf(`
		SELECT tenant_id, node_id, type_id, payload_json,
		       created_at, updated_at, owner_actor, acl_blob
		FROM nodes
		WHERE tenant_id = ? AND node_id IN (%s)`, placeholders)
	rows, err := db.QueryContext(ctx, q, args...)
	if err != nil {
		return nil, nil, fmt.Errorf("store: GetNodes: %w", err)
	}
	defer rows.Close()
	seen := map[string]struct{}{}
	for rows.Next() {
		n := &Node{}
		if err := rows.Scan(&n.TenantID, &n.NodeID, &n.TypeID, &n.PayloadJSON,
			&n.CreatedAt, &n.UpdatedAt, &n.OwnerActor, &n.ACLJSON); err != nil {
			return nil, nil, fmt.Errorf("store: GetNodes scan: %w", err)
		}
		nodes = append(nodes, n)
		seen[n.NodeID] = struct{}{}
	}
	if err := rows.Err(); err != nil {
		return nil, nil, fmt.Errorf("store: GetNodes rows: %w", err)
	}
	for _, id := range nodeIDs {
		if _, ok := seen[id]; !ok {
			missing = append(missing, id)
		}
	}
	return nodes, missing, nil
}

// QueryNodesArgs is the input to QueryNodes. Mirrors
// canonical_store.py:_sync_query_nodes (2394) signature minus the
// MongoDB filter (deferred to W1.10 query_filter port).
type QueryNodesArgs struct {
	TenantID string
	TypeID   int32
	// EqualityFilters apply ``json_extract(payload_json, '$."<field_id>"') = ?``
	// for each entry. Field ids and equality-only filters are the
	// minimum surface needed by Wave 2 read handlers; the full
	// MongoDB-operator allow-list lives in W1.10 (see
	// docs/go-port/rpcs/QueryNodes.md).
	EqualityFilters map[uint32]any
	OrderBy         string // one of {"created_at","updated_at","node_id","type_id"}; default created_at
	Descending      bool
	Limit           int
	Offset          int
}

// QueryNodes returns up to args.Limit nodes of args.TypeID, optionally
// filtered by per-field equality. SQL injection is prevented by an
// allow-list on OrderBy and parameterised values everywhere else.
func (s *CanonicalStore) QueryNodes(ctx context.Context, args QueryNodesArgs) ([]*Node, error) {
	db, err := s.db(args.TenantID)
	if err != nil {
		return nil, err
	}
	orderBy := args.OrderBy
	switch orderBy {
	case "created_at", "updated_at", "node_id", "type_id":
		// allowed
	default:
		orderBy = "created_at"
	}
	dir := "DESC"
	if !args.Descending {
		dir = "ASC"
	}
	limit := args.Limit
	if limit <= 0 {
		limit = 100
	}

	whereParts := []string{"tenant_id = ?", "type_id = ?"}
	params := []any{args.TenantID, args.TypeID}
	for fid, val := range args.EqualityFilters {
		whereParts = append(whereParts, fmt.Sprintf(
			`json_extract(payload_json, '$."%d"') = ?`, fid,
		))
		params = append(params, val)
	}
	params = append(params, limit, args.Offset)

	q := fmt.Sprintf(`
		SELECT tenant_id, node_id, type_id, payload_json,
		       created_at, updated_at, owner_actor, acl_blob
		FROM nodes WHERE %s
		ORDER BY %s %s LIMIT ? OFFSET ?`,
		strings.Join(whereParts, " AND "), orderBy, dir,
	)
	rows, err := db.QueryContext(ctx, q, params...)
	if err != nil {
		return nil, fmt.Errorf("store: QueryNodes: %w", err)
	}
	defer rows.Close()
	var out []*Node
	for rows.Next() {
		n := &Node{}
		if err := rows.Scan(&n.TenantID, &n.NodeID, &n.TypeID, &n.PayloadJSON,
			&n.CreatedAt, &n.UpdatedAt, &n.OwnerActor, &n.ACLJSON); err != nil {
			return nil, fmt.Errorf("store: QueryNodes scan: %w", err)
		}
		out = append(out, n)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("store: QueryNodes rows: %w", err)
	}
	return out, nil
}

// CreateNodeRaw inserts a node row using a field-id-keyed payload.
// Mirrors canonical_store.py:create_node_raw (1291). Caller is expected
// to be the applier; the payload must already be id-keyed (CLAUDE.md
// invariant #6). updates the node_visibility index for owner + ACL
// principals.
//
// CreatedAt defaults to s.now() when zero.
func (s *CanonicalStore) CreateNodeRaw(ctx context.Context, tenantID string, in NodeInput) (*Node, error) {
	if in.OwnerActor == "" {
		return nil, fmt.Errorf("store: CreateNodeRaw: owner_actor required")
	}
	if in.NodeID == "" {
		return nil, fmt.Errorf("store: CreateNodeRaw: node_id required (caller assigns)")
	}
	now := in.CreatedAt
	if now == 0 {
		now = s.now()
	}
	payload := in.Payload
	if payload == nil {
		payload = map[string]any{}
	}
	payloadStr, err := json.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("store: marshal payload: %w", err)
	}
	acl := in.ACL
	if acl == nil {
		acl = []ACLEntry{}
	}
	aclStr, err := json.Marshal(acl)
	if err != nil {
		return nil, fmt.Errorf("store: marshal acl: %w", err)
	}

	if err := s.ensureFieldIndexes(ctx, tenantID, in.TypeID); err != nil {
		return nil, err
	}

	err = s.withWrite(ctx, tenantID, func(conn *sql.Conn) error {
		_, err := conn.ExecContext(ctx, `
			INSERT INTO nodes (tenant_id, node_id, type_id, payload_json,
			                   created_at, updated_at, owner_actor, acl_blob)
			VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
			tenantID, in.NodeID, in.TypeID, string(payloadStr),
			now, now, in.OwnerActor, string(aclStr),
		)
		if err != nil {
			if isUniqueViolation(err) {
				return fmt.Errorf("%w: %s/%s", ErrUniqueConstraint, tenantID, in.NodeID)
			}
			return fmt.Errorf("store: insert node: %w", err)
		}
		return updateVisibilityWithConn(ctx, conn, tenantID, in.NodeID, in.OwnerActor, acl)
	})
	if err != nil {
		return nil, err
	}
	return &Node{
		TenantID:    tenantID,
		NodeID:      in.NodeID,
		TypeID:      in.TypeID,
		PayloadJSON: string(payloadStr),
		CreatedAt:   now,
		UpdatedAt:   now,
		OwnerActor:  in.OwnerActor,
		ACLJSON:     string(aclStr),
	}, nil
}

// UpdateNode applies a PATCH-style partial payload merge. Mirrors
// canonical_store.py:_sync_update_node (1612). Returns ErrNodeNotFound
// if the row does not exist. patch is field-id-keyed (string keys).
func (s *CanonicalStore) UpdateNode(ctx context.Context, tenantID, nodeID string, patch map[string]any) (*Node, error) {
	if patch == nil {
		patch = map[string]any{}
	}
	now := s.now()
	var updated *Node
	err := s.withWrite(ctx, tenantID, func(conn *sql.Conn) error {
		row := conn.QueryRowContext(ctx, `
			SELECT tenant_id, node_id, type_id, payload_json,
			       created_at, owner_actor, acl_blob
			FROM nodes WHERE tenant_id = ? AND node_id = ?`,
			tenantID, nodeID,
		)
		var (
			tID, nID, ownerActor   string
			typeID                 int32
			payloadJSON, aclJSON   string
			createdAt              int64
		)
		err := row.Scan(&tID, &nID, &typeID, &payloadJSON, &createdAt, &ownerActor, &aclJSON)
		if errors.Is(err, sql.ErrNoRows) {
			return fmt.Errorf("%w: %s/%s", ErrNodeNotFound, tenantID, nodeID)
		}
		if err != nil {
			return fmt.Errorf("store: select-for-update node: %w", err)
		}
		// Merge payload.
		merged := map[string]any{}
		if err := json.Unmarshal([]byte(payloadJSON), &merged); err != nil {
			return fmt.Errorf("store: parse existing payload: %w", err)
		}
		for k, v := range patch {
			merged[k] = v
		}
		mergedStr, err := json.Marshal(merged)
		if err != nil {
			return fmt.Errorf("store: marshal merged payload: %w", err)
		}
		_, err = conn.ExecContext(ctx, `
			UPDATE nodes SET payload_json = ?, updated_at = ?
			WHERE tenant_id = ? AND node_id = ?`,
			string(mergedStr), now, tenantID, nodeID,
		)
		if err != nil {
			return fmt.Errorf("store: update node: %w", err)
		}
		updated = &Node{
			TenantID:    tenantID,
			NodeID:      nodeID,
			TypeID:      typeID,
			PayloadJSON: string(mergedStr),
			CreatedAt:   createdAt,
			UpdatedAt:   now,
			OwnerActor:  ownerActor,
			ACLJSON:     aclJSON,
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	return updated, nil
}

// DeleteNode removes a node row, cascades edges, visibility, and ACL
// rows. Mirrors canonical_store.py:_sync_delete_node (1688). Returns
// ErrNodeNotFound if the row did not exist.
func (s *CanonicalStore) DeleteNode(ctx context.Context, tenantID, nodeID string) error {
	return s.withWrite(ctx, tenantID, func(conn *sql.Conn) error {
		if _, err := conn.ExecContext(ctx,
			`DELETE FROM edges WHERE tenant_id = ? AND (from_node_id = ? OR to_node_id = ?)`,
			tenantID, nodeID, nodeID,
		); err != nil {
			return fmt.Errorf("store: delete edges: %w", err)
		}
		if _, err := conn.ExecContext(ctx,
			`DELETE FROM node_visibility WHERE tenant_id = ? AND node_id = ?`,
			tenantID, nodeID,
		); err != nil {
			return fmt.Errorf("store: delete visibility: %w", err)
		}
		if _, err := conn.ExecContext(ctx,
			`DELETE FROM node_access WHERE node_id = ?`, nodeID,
		); err != nil {
			return fmt.Errorf("store: delete node_access: %w", err)
		}
		if _, err := conn.ExecContext(ctx,
			`DELETE FROM acl_inherit WHERE node_id = ?`, nodeID,
		); err != nil {
			return fmt.Errorf("store: delete acl_inherit: %w", err)
		}
		res, err := conn.ExecContext(ctx,
			`DELETE FROM nodes WHERE tenant_id = ? AND node_id = ?`,
			tenantID, nodeID,
		)
		if err != nil {
			return fmt.Errorf("store: delete node: %w", err)
		}
		n, _ := res.RowsAffected()
		if n == 0 {
			return fmt.Errorf("%w: %s/%s", ErrNodeNotFound, tenantID, nodeID)
		}
		return nil
	})
}

// CountOwnedNodes returns the number of `nodes` rows where
// `owner_actor = ownerActor` inside `tenantID`. Read-only — used by
// TransferUserContent to compute the pre-apply count returned to the
// caller (mirrors grpc_server.py:2727-2736).
//
// On a missing tenant DB the function returns (0, nil) — the user
// transparently owns nothing in a tenant we have not seen — matching
// the Python handler's "swallow + return 0" failure mode.
func (s *CanonicalStore) CountOwnedNodes(ctx context.Context, tenantID, ownerActor string) (int32, error) {
	if tenantID == "" || ownerActor == "" {
		return 0, nil
	}
	db, err := s.db(tenantID)
	if err != nil {
		// Tenant file not yet open: treat as zero-owned for parity.
		return 0, nil
	}
	var n int32
	row := db.QueryRowContext(ctx,
		`SELECT COUNT(*) FROM nodes WHERE tenant_id = ? AND owner_actor = ?`,
		tenantID, ownerActor,
	)
	if err := row.Scan(&n); err != nil {
		return 0, fmt.Errorf("store: CountOwnedNodes: %w", err)
	}
	return n, nil
}

// ListOwnedNodeIDs returns the node_ids in `tenantID` whose
// `owner_actor = ownerActor`. The slice is unordered. Used by
// TransferUserContent to chunk a bulk transfer into multiple WAL
// events when the owned-set is large.
func (s *CanonicalStore) ListOwnedNodeIDs(ctx context.Context, tenantID, ownerActor string) ([]string, error) {
	if tenantID == "" || ownerActor == "" {
		return nil, nil
	}
	db, err := s.db(tenantID)
	if err != nil {
		return nil, nil
	}
	rows, err := db.QueryContext(ctx,
		`SELECT node_id FROM nodes WHERE tenant_id = ? AND owner_actor = ?`,
		tenantID, ownerActor,
	)
	if err != nil {
		return nil, fmt.Errorf("store: ListOwnedNodeIDs: %w", err)
	}
	defer rows.Close()
	var ids []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, fmt.Errorf("store: ListOwnedNodeIDs scan: %w", err)
		}
		ids = append(ids, id)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("store: ListOwnedNodeIDs rows: %w", err)
	}
	return ids, nil
}

// TenantExportNode is one row in the per-tenant export bundle assembled
// by ExportUserData. Mirrors the dict shape returned by Python
// _sync_export_user_data (canonical_store.py:5223-5234):
//
//	{ tenant_id, node_id, type_id, payload, created_at, updated_at,
//	  owner_actor, data_policy }
//
// `Payload` is field-id-keyed (CLAUDE.md invariant #6) — the JSON
// returned to the client preserves the on-disk shape verbatim.
type TenantExportNode struct {
	TenantID   string         `json:"tenant_id"`
	NodeID     string         `json:"node_id"`
	TypeID     int32          `json:"type_id"`
	Payload    map[string]any `json:"payload"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
	OwnerActor string         `json:"owner_actor"`
	DataPolicy string         `json:"data_policy"`
}

// TenantExport is the per-tenant slice of the cross-tenant
// ExportUserData bundle. Mirrors `{tenant_id, nodes}` returned by
// canonical_store.export_user_data_for_tenant (canonical_store.py:5236).
type TenantExport struct {
	TenantID string             `json:"tenant_id"`
	Nodes    []TenantExportNode `json:"nodes"`
}

// ExportUserData collects every node in `tenantID` that the caller
// owns or is the subject of, excluding `data_policy=audit` types.
// Port of canonical_store.py:_sync_export_user_data (5174-5236).
//
// `principal` is the per-tenant principal form (`user:<id>`). `reg` is
// the schema registry used for data-policy / subject-field lookups; nil
// is permitted and triggers the same fall-back as Python's KeyError
// branch (DataPolicyPersonal, no subject field).
//
// The returned `Nodes` slice is non-nil even when empty — JSON consumers
// expect `[]`, not `null`, to match the Python `json.dumps([])` shape.
func (s *CanonicalStore) ExportUserData(
	ctx context.Context,
	tenantID, principal string,
	reg *schema.Registry,
) (TenantExport, error) {
	out := TenantExport{TenantID: tenantID, Nodes: []TenantExportNode{}}
	db, err := s.db(tenantID)
	if err != nil {
		return out, err
	}
	rows, err := db.QueryContext(ctx, `
		SELECT node_id, type_id, payload_json,
		       created_at, updated_at, owner_actor
		FROM nodes WHERE tenant_id = ?`,
		tenantID,
	)
	if err != nil {
		return out, fmt.Errorf("store: ExportUserData: %w", err)
	}
	defer rows.Close()
	for rows.Next() {
		var (
			nodeID, payloadJSON, owner string
			typeID                     int32
			createdAt, updatedAt       int64
		)
		if err := rows.Scan(&nodeID, &typeID, &payloadJSON, &createdAt, &updatedAt, &owner); err != nil {
			return out, fmt.Errorf("store: ExportUserData scan: %w", err)
		}

		// Schema lookups: missing type → PERSONAL, no subject field.
		// Mirrors the KeyError fallback at canonical_store.py:5206-5208.
		var (
			policy       schema.DataPolicy = schema.DataPolicyPersonal
			subjectField string
		)
		if reg != nil {
			if nt := reg.NodeTypeByID(typeID); nt != nil {
				policy = reg.DataPolicyOf(typeID)
				subjectField = reg.SubjectField(typeID)
			}
		}

		// AUDIT records are NOT subject-access-requestable (ADR-004).
		if policy == schema.DataPolicyAudit {
			continue
		}

		payload := map[string]any{}
		if payloadJSON != "" {
			// Best-effort parse: a malformed payload becomes {} rather
			// than failing the whole export — matches Python's
			// json.JSONDecodeError swallow at canonical_store.py:5212-5213.
			_ = json.Unmarshal([]byte(payloadJSON), &payload)
		}

		isOwner := owner == principal
		isSubject := false
		if subjectField != "" {
			// Latent-bug parity: Python compares payload[subject_field]
			// to the *user_id* (bare, e.g. "alice"), not the principal
			// (`user:alice`). See canonical_store.py:5216 and the spec's
			// Open Question #6. We replicate exactly: strip the
			// `user:` prefix from `principal` before comparing.
			subjectID := principal
			if len(subjectID) > 5 && subjectID[:5] == "user:" {
				subjectID = subjectID[5:]
			}
			if v, ok := payload[subjectField]; ok && v == subjectID {
				isSubject = true
			}
		}
		if !(isOwner || isSubject) {
			continue
		}

		out.Nodes = append(out.Nodes, TenantExportNode{
			TenantID:   tenantID,
			NodeID:     nodeID,
			TypeID:     typeID,
			Payload:    payload,
			CreatedAt:  createdAt,
			UpdatedAt:  updatedAt,
			OwnerActor: owner,
			DataPolicy: string(policy),
		})
	}
	if err := rows.Err(); err != nil {
		return out, fmt.Errorf("store: ExportUserData rows: %w", err)
	}
	return out, nil
}

// isUniqueViolation reports whether err is a SQLite UNIQUE-constraint
// failure. modernc.org/sqlite returns errors whose messages contain
// "constraint failed: UNIQUE" — we string-match because the driver does
// not export typed sentinels for these.
func isUniqueViolation(err error) bool {
	if err == nil {
		return false
	}
	msg := err.Error()
	return strings.Contains(msg, "UNIQUE constraint failed") ||
		strings.Contains(msg, "constraint failed: UNIQUE")
}
