package store

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"strconv"
	"strings"

	"github.com/elloloop/tenant-shard-db/server/go/internal/jsonnum"
	"github.com/elloloop/tenant-shard-db/server/go/internal/schema"
)

// Node is the in-Go representation of one row of the `nodes` table.
// Field-id-keyed payload JSON is exposed verbatim — the wire stays
// field_id-keyed too (name-free, ADR-031); the SDK resolves names
// client-side from its proto (CLAUDE.md invariant #6).
// StorageMode classifies which physical store a node belongs to. The
// integer values mirror entdb.v1.StorageMode on the wire so the column
// round-trips the proto enum without translation. The store package owns
// its own copy (rather than importing pb) to keep the dependency arrow
// pointing pb -> store, never the reverse.
type StorageMode int32

const (
	// StorageModeTenant — node lives in the per-tenant SQLite file and is
	// sharable via ACL within the tenant. The zero value, so every legacy
	// row and every caller that omits the field is a plain tenant node.
	StorageModeTenant StorageMode = 0
	// StorageModeUserMailbox — node is private to exactly one user
	// (target_user_id). Tenant-backed today (ADR-014): the row lives in
	// the tenant file, scoped by target_user_id, not a separate per-user
	// SQLite file.
	StorageModeUserMailbox StorageMode = 1
	// StorageModePublic — reserved for the singleton public store (not
	// generally enabled per ADR-014).
	StorageModePublic StorageMode = 2
)

type Node struct {
	TenantID    string
	NodeID      string
	TypeID      int32
	PayloadJSON string // raw JSON, keyed by field_id
	CreatedAt   int64  // unix ms
	UpdatedAt   int64  // unix ms
	OwnerActor  string
	ACLJSON     string // raw JSON list of {principal, permission} entries
	// StorageMode mirrors entdb.v1.StorageMode (0=TENANT, 1=USER_MAILBOX,
	// 2=PUBLIC). TargetUserID is the owning user for USER_MAILBOX nodes
	// and "" for every other mode. Both are immutable after creation
	// (ADR-020).
	StorageMode  int32
	TargetUserID string
}

// NodeInput is the input shape of CreateNodeRaw. The payload map must
// already be field-id-keyed (string keys for JSON marshalling, e.g.
// {"1": "alice"}).
type NodeInput struct {
	NodeID     string         // optional — generated by caller (e.g. UUID)
	TypeID     int32          // required
	Payload    map[string]any // field-id-keyed
	OwnerActor string         // required
	ACL        []ACLEntry     // optional, default []
	CreatedAt  int64          // optional, defaults to now()
	// StorageMode/TargetUserID classify where the node lives (ADR-020).
	// Default (0, "") creates a plain TENANT node, preserving the
	// behaviour of every pre-existing caller. TargetUserID MUST be set
	// when StorageMode is USER_MAILBOX (1).
	StorageMode  int32
	TargetUserID string
}

// scanner is the minimal surface shared by *sql.Row and *sql.Rows.
type scanner interface {
	Scan(dest ...any) error
}

// scanNode reads one node row in the canonical column order. Every read
// path uses this so adding a column is a single edit, not a fan-out of
// brittle Scan() lists.
func scanNode(sc scanner) (*Node, error) {
	n := &Node{}
	if err := sc.Scan(&n.TenantID, &n.NodeID, &n.TypeID, &n.PayloadJSON,
		&n.CreatedAt, &n.UpdatedAt, &n.OwnerActor, &n.ACLJSON,
		&n.StorageMode, &n.TargetUserID); err != nil {
		return nil, err
	}
	return n, nil
}

// nodeColumns is the SELECT projection shared by all node read paths. It
// must stay positionally aligned with scanNode.
const nodeColumns = `tenant_id, node_id, type_id, payload_json,
	created_at, updated_at, owner_actor, acl_blob,
	storage_mode, target_user_id`

// ACLEntry mirrors the per-node `acl_blob` JSON shape ({principal,
// permission}). Stored verbatim alongside the node row; full ACL
// evaluation lives in the acl package.
type ACLEntry struct {
	Principal  string `json:"principal"`
	Permission string `json:"permission"`
}

// GetNode fetches one node by (tenant, node_id). Returns ErrNodeNotFound
// (NotFound) when missing.
func (s *CanonicalStore) GetNode(ctx context.Context, tenantID, nodeID string) (*Node, error) {
	db, err := s.readDB(tenantID)
	if err != nil {
		return nil, err
	}
	row := db.QueryRowContext(ctx, `
		SELECT `+nodeColumns+`
		FROM nodes WHERE tenant_id = ? AND node_id = ?`,
		tenantID, nodeID,
	)
	n, err := scanNode(row)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, fmt.Errorf("%w: %s/%s", ErrNodeNotFound, tenantID, nodeID)
	}
	if err != nil {
		return nil, fmt.Errorf("store: GetNode: %w", err)
	}
	return n, nil
}

// GetMailboxNode fetches one node by (tenant, node_id) and enforces that
// it belongs to targetUser's mailbox. Returns ErrNodeNotFound when the
// row is missing OR is not a USER_MAILBOX node owned by targetUser — the
// caller cannot distinguish "absent" from "not yours", which is the
// intended privacy boundary for mailbox-scoped reads.
func (s *CanonicalStore) GetMailboxNode(ctx context.Context, tenantID, targetUser, nodeID string) (*Node, error) {
	n, err := s.GetNode(ctx, tenantID, nodeID)
	if err != nil {
		return nil, err
	}
	if n.TargetUserID != targetUser || n.StorageMode != int32(StorageModeUserMailbox) {
		return nil, fmt.Errorf("%w: %s/%s", ErrNodeNotFound, tenantID, nodeID)
	}
	return n, nil
}

// GetNodeByKey resolves a node via its declared unique field. Returns
// (nil, nil)
// when no row matches the (tenant, type, field, value) tuple — the
// miss is signalled in-band so the caller can decide between
// PERMISSION_DENIED, NOT_FOUND, or in-band found=false (the
// GetNodeByKey RPC chooses found=false; see
// docs/go-port/rpcs/GetNodeByKey.md).
//
// The lookup is byte-exact: SQLite TEXT comparison is case-sensitive
// without an explicit COLLATE NOCASE, and we add none. Callers (SDKs)
// own client-side normalisation (lowercased email, trimmed
// whitespace) per docs/decisions/unique_keys.md:90-92.
//
// The query reaches for the partial unique expression index lazily
// created by EnsureUniqueIndex. This method does NOT call
// EnsureUniqueIndex itself — the index must already exist (the
// applier creates it on the write path). Without the index the
// SELECT still works but degrades to a scan.
func (s *CanonicalStore) GetNodeByKey(ctx context.Context, tenantID string, typeID, fieldID int32, value any) (*Node, error) {
	db, err := s.readDB(tenantID)
	if err != nil {
		return nil, err
	}
	q := fmt.Sprintf(`
		SELECT `+nodeColumns+`
		FROM nodes
		WHERE tenant_id = ? AND type_id = ?
		  AND json_extract(payload_json, '$."%d"') = ?
		LIMIT 1`, fieldID)
	row := db.QueryRowContext(ctx, q, tenantID, typeID, value)
	n, err := scanNode(row)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("store: GetNodeByKey: %w", err)
	}
	return n, nil
}

// GetNodeByCompositeKey resolves a node via a multi-field composite
// unique tuple. Same byte-exact contract as GetNodeByKey. Returns
// (nil, nil) on miss; (nil, error) only on infra failure.
//
// fieldIDs and values must be the same non-zero length; an empty or
// length-mismatched input returns (nil, errs.ErrInvalidArgument).
func (s *CanonicalStore) GetNodeByCompositeKey(ctx context.Context, tenantID string, typeID int32, fieldIDs []int32, values []any) (*Node, error) {
	if len(fieldIDs) == 0 || len(fieldIDs) != len(values) {
		return nil, fmt.Errorf("store: GetNodeByCompositeKey: field_ids/values length mismatch (%d vs %d)", len(fieldIDs), len(values))
	}
	db, err := s.readDB(tenantID)
	if err != nil {
		return nil, err
	}
	clauses := make([]string, 0, len(fieldIDs))
	for _, fid := range fieldIDs {
		clauses = append(clauses, fmt.Sprintf(`json_extract(payload_json, '$."%d"') = ?`, fid))
	}
	args := make([]any, 0, 2+len(values))
	args = append(args, tenantID, typeID)
	args = append(args, values...)
	q := fmt.Sprintf(`
		SELECT `+nodeColumns+`
		FROM nodes
		WHERE tenant_id = ? AND type_id = ?
		  AND %s
		LIMIT 1`, strings.Join(clauses, " AND "))
	row := db.QueryRowContext(ctx, q, args...)
	n, err := scanNode(row)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("store: GetNodeByCompositeKey: %w", err)
	}
	return n, nil
}

// GetNodes batch-fetches nodes by id. Returns the nodes that exist plus
// the list of missing ids (for caller-side NotFound reporting). Order
// of returned nodes is unspecified.
func (s *CanonicalStore) GetNodes(ctx context.Context, tenantID string, nodeIDs []string) (nodes []*Node, missing []string, err error) {
	if len(nodeIDs) == 0 {
		return nil, nil, nil
	}
	db, err := s.readDB(tenantID)
	if err != nil {
		return nil, nil, err
	}
	placeholders := strings.Repeat("?,", len(nodeIDs))
	placeholders = placeholders[:len(placeholders)-1]
	args := make([]any, 0, len(nodeIDs)+1)
	args = append(args, tenantID)
	for _, id := range nodeIDs {
		args = append(args, id)
	}
	q := fmt.Sprintf(`
		SELECT `+nodeColumns+`
		FROM nodes
		WHERE tenant_id = ? AND node_id IN (%s)`, placeholders)
	rows, err := db.QueryContext(ctx, q, args...)
	if err != nil {
		return nil, nil, fmt.Errorf("store: GetNodes: %w", err)
	}
	defer rows.Close()
	seen := map[string]struct{}{}
	for rows.Next() {
		n, err := scanNode(rows)
		if err != nil {
			return nil, nil, fmt.Errorf("store: GetNodes scan: %w", err)
		}
		nodes = append(nodes, n)
		seen[n.NodeID] = struct{}{}
	}
	if err := rows.Err(); err != nil {
		return nil, nil, fmt.Errorf("store: GetNodes rows: %w", err)
	}
	for _, id := range nodeIDs {
		if _, ok := seen[id]; !ok {
			missing = append(missing, id)
		}
	}
	return nodes, missing, nil
}

// QueryFilterOp is the comparison operator carried by a [QueryFilter].
// The values map 1:1 to SQL comparison operators on a
// “json_extract(payload_json, '$."<field_id>"')“ expression.
type QueryFilterOp uint8

const (
	// QueryFilterEq compiles to ``=``. The default when an operator
	// is unset.
	QueryFilterEq QueryFilterOp = iota
	// QueryFilterNe compiles to ``<>``. Cannot use a B-tree index
	// — forces a scan over the type's rows.
	QueryFilterNe
	// QueryFilterLt compiles to ``<``.
	QueryFilterLt
	// QueryFilterLe compiles to ``<=``.
	QueryFilterLe
	// QueryFilterGt compiles to ``>``.
	QueryFilterGt
	// QueryFilterGe compiles to ``>=``.
	QueryFilterGe
)

// sqlOp returns the SQL operator for the receiver. Defaults to “=“.
func (op QueryFilterOp) sqlOp() string {
	switch op {
	case QueryFilterNe:
		return "<>"
	case QueryFilterLt:
		return "<"
	case QueryFilterLe:
		return "<="
	case QueryFilterGt:
		return ">"
	case QueryFilterGe:
		return ">="
	default:
		return "="
	}
}

// QueryFilter is one AND-ed predicate evaluated by [CanonicalStore.QueryNodes].
// FieldID is the on-disk payload field id (CLAUDE.md invariant #6);
// Op is the comparison operator; Value is bound as a SQLite parameter.
type QueryFilter struct {
	FieldID uint32
	Op      QueryFilterOp
	Value   any
}

// storeMaxQueryLimit is the defence-in-depth ceiling QueryNodes applies
// to args.Limit (SEC-4, issue #135). It mirrors api.MaxPageSize (1000)
// but is duplicated here on purpose: the store package must not import
// the api package (that would invert the dependency direction). The two
// values are kept in lock-step by the store-layer clamp test.
const storeMaxQueryLimit = 1000

// CompileQueryFilters lowers a [QueryFilter] slice into AND-able SQL
// predicate fragments and their bound parameters. Each filter compiles
// to “json_extract(payload_json, '$."<field_id>"') <op> ?“ — the same
// shape [CanonicalStore.QueryNodes] builds inline, factored out so the
// applier's predicate-based sweeper (OpDeleteWhere, GitHub issue #504)
// reuses the identical, injection-safe construction. The returned
// clauses and params are positionally aligned with `filters`.
func CompileQueryFilters(filters []QueryFilter) (clauses []string, params []any) {
	if len(filters) == 0 {
		return nil, nil
	}
	clauses = make([]string, 0, len(filters))
	params = make([]any, 0, len(filters))
	for _, f := range filters {
		clauses = append(clauses, fmt.Sprintf(
			`json_extract(payload_json, '$."%d"') %s ?`, f.FieldID, f.Op.sqlOp(),
		))
		params = append(params, f.Value)
	}
	return clauses, params
}

// QueryNodesArgs is the input to QueryNodes.
type QueryNodesArgs struct {
	TenantID string
	TypeID   int32
	// EqualityFilters apply ``json_extract(payload_json, '$."<field_id>"') = ?``
	// for each entry. Equality-only — kept for backwards compatibility
	// with existing call sites that only need the equality shape.
	EqualityFilters map[uint32]any
	// Filters carries comparison predicates (Eq/Ne/Lt/Le/Gt/Ge). All
	// filters are AND-ed together, and AND-ed with EqualityFilters when
	// both are supplied. Multiple filters on the same field are
	// permitted (a range is expressed as two filters: ``x >= lo`` AND
	// ``x < hi``). See issue #501.
	Filters    []QueryFilter
	OrderBy    string // one of {"created_at","updated_at","node_id","type_id"}; default created_at
	Descending bool
	Limit      int
	Offset     int

	// MailboxUser scopes the query to a single user's mailbox when set:
	// only USER_MAILBOX nodes with target_user_id == MailboxUser match.
	// Empty (the default) leaves the query unscoped, so every existing
	// caller is unaffected — tenant reads never see mailbox-private rows
	// only because nothing sets target_user_id on tenant nodes.
	MailboxUser string

	// Keyset cursor (ADR-029). When Cursor != nil the query seeks past
	// the (Cursor.OrderValue, Cursor.NodeID) tuple instead of applying
	// Offset — a stable continuation that never skips or duplicates a row
	// under concurrent writes. Offset is ignored when Cursor is set.
	Cursor *QueryCursor
}

// QueryCursor anchors a keyset seek: the effective order-by value and
// node_id of the last row returned by the previous page. The store
// resumes at the row strictly after this tuple in the effective sort
// order (ascending or descending per Descending on the args).
type QueryCursor struct {
	OrderValue any
	NodeID     string
}

// EffectiveOrderBy resolves a requested order_by to the column actually
// used, applying the allow-list (default created_at). It is the single
// source of truth shared by QueryNodes and the keyset-cursor machinery
// in the api layer so the cursor anchor always matches the SQL ORDER BY.
func EffectiveOrderBy(orderBy string) string {
	switch orderBy {
	case "created_at", "updated_at", "node_id", "type_id":
		return orderBy
	default:
		return "created_at"
	}
}

// NodeOrderValue returns the value of n's effective order column — the
// anchor a keyset cursor stores so the next page can seek past it.
func NodeOrderValue(n *Node, orderBy string) any {
	switch EffectiveOrderBy(orderBy) {
	case "updated_at":
		return n.UpdatedAt
	case "node_id":
		return n.NodeID
	case "type_id":
		return n.TypeID
	default: // created_at
		return n.CreatedAt
	}
}

// QueryNodes returns up to args.Limit nodes of args.TypeID, optionally
// filtered by per-field equality. SQL injection is prevented by an
// allow-list on OrderBy and parameterised values everywhere else.
func (s *CanonicalStore) QueryNodes(ctx context.Context, args QueryNodesArgs) ([]*Node, error) {
	db, err := s.readDB(args.TenantID)
	if err != nil {
		return nil, err
	}
	orderBy := EffectiveOrderBy(args.OrderBy)
	dir := "DESC"
	cmp := "<"
	if !args.Descending {
		dir = "ASC"
		cmp = ">"
	}
	limit := args.Limit
	if limit <= 0 {
		limit = 100
	}
	// SEC-4 (#135) defence-in-depth: the gRPC handlers already clamp to
	// api.MaxPageSize, but re-apply the same ceiling here so any future
	// in-process caller that bypasses the handler still cannot ask the
	// SQLite layer to materialise an unbounded result set. Kept as a
	// package-local literal (the store package must not import api).
	if limit > storeMaxQueryLimit {
		limit = storeMaxQueryLimit
	}

	whereParts := []string{"tenant_id = ?", "type_id = ?"}
	params := []any{args.TenantID, args.TypeID}
	// Mailbox scope (#568, ADR-020). USER_MAILBOX nodes are private to one
	// user and must never leak into a tenant-scoped read:
	//   - MailboxUser set -> return ONLY that user's mailbox nodes.
	//   - MailboxUser empty -> a tenant query EXCLUDES every mailbox node
	//     (storage_mode <> USER_MAILBOX), so mailbox-private rows are
	//     reachable only through the explicit mailbox scope.
	if args.MailboxUser != "" {
		whereParts = append(whereParts, "target_user_id = ?", "storage_mode = ?")
		params = append(params, args.MailboxUser, int32(StorageModeUserMailbox))
	} else {
		whereParts = append(whereParts, "storage_mode <> ?")
		params = append(params, int32(StorageModeUserMailbox))
	}
	for fid, val := range args.EqualityFilters {
		whereParts = append(whereParts, fmt.Sprintf(
			`json_extract(payload_json, '$."%d"') = ?`, fid,
		))
		params = append(params, val)
	}
	if fClauses, fParams := CompileQueryFilters(args.Filters); len(fClauses) > 0 {
		whereParts = append(whereParts, fClauses...)
		params = append(params, fParams...)
	}

	// Keyset seek (ADR-029) vs legacy OFFSET. node_id is unique and is
	// always the final sort key, so (orderBy, node_id) is a total order
	// and the seek resumes unambiguously at the row strictly after the
	// cursor. When orderBy *is* node_id the two collapse to a single
	// column. The expanded ``col cmp ? OR (col = ? AND node_id cmp ?)``
	// form avoids relying on SQLite row-value tuple comparison and stays
	// index-friendly.
	var tail string
	if args.Cursor != nil {
		if orderBy == "node_id" {
			whereParts = append(whereParts, fmt.Sprintf("node_id %s ?", cmp))
			params = append(params, args.Cursor.NodeID)
		} else {
			whereParts = append(whereParts, fmt.Sprintf(
				"(%s %s ? OR (%s = ? AND node_id %s ?))", orderBy, cmp, orderBy, cmp))
			params = append(params, args.Cursor.OrderValue, args.Cursor.OrderValue, args.Cursor.NodeID)
		}
		params = append(params, limit)
		tail = "LIMIT ?"
	} else {
		params = append(params, limit, args.Offset)
		tail = "LIMIT ? OFFSET ?"
	}

	orderClause := fmt.Sprintf("%s %s", orderBy, dir)
	if orderBy != "node_id" {
		orderClause += fmt.Sprintf(", node_id %s", dir)
	}
	q := fmt.Sprintf(`
		SELECT `+nodeColumns+`
		FROM nodes WHERE %s
		ORDER BY %s %s`,
		strings.Join(whereParts, " AND "), orderClause, tail,
	)
	rows, err := db.QueryContext(ctx, q, params...)
	if err != nil {
		return nil, fmt.Errorf("store: QueryNodes: %w", err)
	}
	defer rows.Close()
	var out []*Node
	for rows.Next() {
		n, err := scanNode(rows)
		if err != nil {
			return nil, fmt.Errorf("store: QueryNodes scan: %w", err)
		}
		out = append(out, n)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("store: QueryNodes rows: %w", err)
	}
	return out, nil
}

// CreateNodeRaw inserts a node row using a field-id-keyed payload.
// Caller is expected to be the applier; the payload must already be
// id-keyed (CLAUDE.md invariant #6). Updates the node_visibility index
// for owner + ACL principals.
//
// CreatedAt defaults to s.now() when zero.
func (s *CanonicalStore) CreateNodeRaw(ctx context.Context, tenantID string, in NodeInput) (*Node, error) {
	if in.OwnerActor == "" {
		return nil, fmt.Errorf("store: CreateNodeRaw: owner_actor required")
	}
	if in.NodeID == "" {
		return nil, fmt.Errorf("store: CreateNodeRaw: node_id required (caller assigns)")
	}
	// A USER_MAILBOX node must name its owning user; a non-mailbox node
	// must NOT carry a target user (ADR-020: storage_mode is the source
	// of truth, target_user_id is meaningful only for mailbox nodes).
	if in.StorageMode == int32(StorageModeUserMailbox) && in.TargetUserID == "" {
		return nil, fmt.Errorf("store: CreateNodeRaw: target_user_id required for USER_MAILBOX")
	}
	if in.StorageMode != int32(StorageModeUserMailbox) && in.TargetUserID != "" {
		return nil, fmt.Errorf("store: CreateNodeRaw: target_user_id only valid for USER_MAILBOX")
	}
	now := in.CreatedAt
	if now == 0 {
		now = s.now()
	}
	payload := in.Payload
	if payload == nil {
		payload = map[string]any{}
	}
	payloadStr, err := json.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("store: marshal payload: %w", err)
	}
	acl := in.ACL
	if acl == nil {
		acl = []ACLEntry{}
	}
	aclStr, err := json.Marshal(acl)
	if err != nil {
		return nil, fmt.Errorf("store: marshal acl: %w", err)
	}

	if err := s.ensureFieldIndexes(ctx, tenantID, in.TypeID); err != nil {
		return nil, err
	}

	err = s.withWrite(ctx, tenantID, func(conn *sql.Conn) error {
		_, err := conn.ExecContext(ctx, `
			INSERT INTO nodes (tenant_id, node_id, type_id, payload_json,
			                   created_at, updated_at, owner_actor, acl_blob,
			                   storage_mode, target_user_id)
			VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
			tenantID, in.NodeID, in.TypeID, string(payloadStr),
			now, now, in.OwnerActor, string(aclStr),
			in.StorageMode, in.TargetUserID,
		)
		if err != nil {
			if isUniqueViolation(err) {
				// Surface the structured ALREADY_EXISTS detail the SDK
				// parsers consume (issue #566) when the violated index is
				// a declared single-field/composite unique constraint;
				// fall back to the generic message otherwise.
				if detail, ok := s.BuildUniqueViolationDetail(tenantID, payload, err); ok {
					return fmt.Errorf("%w: %s", ErrUniqueConstraint, detail)
				}
				return fmt.Errorf("%w: %s/%s", ErrUniqueConstraint, tenantID, in.NodeID)
			}
			return fmt.Errorf("store: insert node: %w", err)
		}
		return updateVisibilityWithConn(ctx, conn, tenantID, in.NodeID, in.OwnerActor, acl)
	})
	if err != nil {
		return nil, err
	}
	return &Node{
		TenantID:     tenantID,
		NodeID:       in.NodeID,
		TypeID:       in.TypeID,
		PayloadJSON:  string(payloadStr),
		CreatedAt:    now,
		UpdatedAt:    now,
		OwnerActor:   in.OwnerActor,
		ACLJSON:      string(aclStr),
		StorageMode:  in.StorageMode,
		TargetUserID: in.TargetUserID,
	}, nil
}

// UpdateNode applies a PATCH-style partial payload merge. Returns
// ErrNodeNotFound if the row does not exist. patch is field-id-keyed
// (string keys).
func (s *CanonicalStore) UpdateNode(ctx context.Context, tenantID, nodeID string, patch map[string]any) (*Node, error) {
	if patch == nil {
		patch = map[string]any{}
	}
	now := s.now()
	var updated *Node
	err := s.withWrite(ctx, tenantID, func(conn *sql.Conn) error {
		row := conn.QueryRowContext(ctx, `
			SELECT tenant_id, node_id, type_id, payload_json,
			       created_at, owner_actor, acl_blob,
			       storage_mode, target_user_id
			FROM nodes WHERE tenant_id = ? AND node_id = ?`,
			tenantID, nodeID,
		)
		var (
			tID, nID, ownerActor string
			typeID               int32
			payloadJSON, aclJSON string
			createdAt            int64
			storageMode          int32
			targetUserID         string
		)
		err := row.Scan(&tID, &nID, &typeID, &payloadJSON, &createdAt, &ownerActor, &aclJSON,
			&storageMode, &targetUserID)
		if errors.Is(err, sql.ErrNoRows) {
			return fmt.Errorf("%w: %s/%s", ErrNodeNotFound, tenantID, nodeID)
		}
		if err != nil {
			return fmt.Errorf("store: select-for-update node: %w", err)
		}
		// Merge payload. Canonical decode (jsonnum) so int64 fields in the
		// existing payload survive the read-modify-write (ADR-028).
		merged, err := jsonnum.Decode([]byte(payloadJSON))
		if err != nil {
			return fmt.Errorf("store: parse existing payload: %w", err)
		}
		for k, v := range patch {
			merged[k] = v
		}
		mergedStr, err := json.Marshal(merged)
		if err != nil {
			return fmt.Errorf("store: marshal merged payload: %w", err)
		}
		_, err = conn.ExecContext(ctx, `
			UPDATE nodes SET payload_json = ?, updated_at = ?
			WHERE tenant_id = ? AND node_id = ?`,
			string(mergedStr), now, tenantID, nodeID,
		)
		if err != nil {
			return fmt.Errorf("store: update node: %w", err)
		}
		updated = &Node{
			TenantID:     tenantID,
			NodeID:       nodeID,
			TypeID:       typeID,
			PayloadJSON:  string(mergedStr),
			CreatedAt:    createdAt,
			UpdatedAt:    now,
			OwnerActor:   ownerActor,
			ACLJSON:      aclJSON,
			StorageMode:  storageMode,
			TargetUserID: targetUserID,
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	return updated, nil
}

// DeleteNode removes a node row, cascades edges, visibility, and ACL
// rows. Returns ErrNodeNotFound if the row did not exist.
func (s *CanonicalStore) DeleteNode(ctx context.Context, tenantID, nodeID string) error {
	return s.withWrite(ctx, tenantID, func(conn *sql.Conn) error {
		if _, err := conn.ExecContext(ctx,
			`DELETE FROM edges WHERE tenant_id = ? AND (from_node_id = ? OR to_node_id = ?)`,
			tenantID, nodeID, nodeID,
		); err != nil {
			return fmt.Errorf("store: delete edges: %w", err)
		}
		if _, err := conn.ExecContext(ctx,
			`DELETE FROM node_visibility WHERE tenant_id = ? AND node_id = ?`,
			tenantID, nodeID,
		); err != nil {
			return fmt.Errorf("store: delete visibility: %w", err)
		}
		if _, err := conn.ExecContext(ctx,
			`DELETE FROM node_access WHERE node_id = ?`, nodeID,
		); err != nil {
			return fmt.Errorf("store: delete node_access: %w", err)
		}
		if _, err := conn.ExecContext(ctx,
			`DELETE FROM acl_inherit WHERE node_id = ?`, nodeID,
		); err != nil {
			return fmt.Errorf("store: delete acl_inherit: %w", err)
		}
		res, err := conn.ExecContext(ctx,
			`DELETE FROM nodes WHERE tenant_id = ? AND node_id = ?`,
			tenantID, nodeID,
		)
		if err != nil {
			return fmt.Errorf("store: delete node: %w", err)
		}
		n, _ := res.RowsAffected()
		if n == 0 {
			return fmt.Errorf("%w: %s/%s", ErrNodeNotFound, tenantID, nodeID)
		}
		return nil
	})
}

// CountOwnedNodes returns the number of `nodes` rows where
// `owner_actor = ownerActor` inside `tenantID`. Read-only — used by
// TransferUserContent to compute the pre-apply count returned to the
// caller.
//
// On a missing tenant DB the function returns (0, nil) — the user
// transparently owns nothing in a tenant we have not seen.
func (s *CanonicalStore) CountOwnedNodes(ctx context.Context, tenantID, ownerActor string) (int32, error) {
	if tenantID == "" || ownerActor == "" {
		return 0, nil
	}
	db, err := s.readDB(tenantID)
	if err != nil {
		// Tenant file not yet open: treat as zero-owned for parity.
		return 0, nil
	}
	var n int32
	row := db.QueryRowContext(ctx,
		`SELECT COUNT(*) FROM nodes WHERE tenant_id = ? AND owner_actor = ?`,
		tenantID, ownerActor,
	)
	if err := row.Scan(&n); err != nil {
		return 0, fmt.Errorf("store: CountOwnedNodes: %w", err)
	}
	return n, nil
}

// ListOwnedNodeIDs returns the node_ids in `tenantID` whose
// `owner_actor = ownerActor`. The slice is unordered. Used by
// TransferUserContent to chunk a bulk transfer into multiple WAL
// events when the owned-set is large.
func (s *CanonicalStore) ListOwnedNodeIDs(ctx context.Context, tenantID, ownerActor string) ([]string, error) {
	if tenantID == "" || ownerActor == "" {
		return nil, nil
	}
	db, err := s.readDB(tenantID)
	if err != nil {
		return nil, nil
	}
	rows, err := db.QueryContext(ctx,
		`SELECT node_id FROM nodes WHERE tenant_id = ? AND owner_actor = ?`,
		tenantID, ownerActor,
	)
	if err != nil {
		return nil, fmt.Errorf("store: ListOwnedNodeIDs: %w", err)
	}
	defer rows.Close()
	var ids []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, fmt.Errorf("store: ListOwnedNodeIDs scan: %w", err)
		}
		ids = append(ids, id)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("store: ListOwnedNodeIDs rows: %w", err)
	}
	return ids, nil
}

// TenantExportNode is one row in the per-tenant export bundle assembled
// by ExportUserData. Shape:
//
//	{ tenant_id, node_id, type_id, payload, created_at, updated_at,
//	  owner_actor, data_policy }
//
// `Payload` is field-id-keyed (CLAUDE.md invariant #6) — the JSON
// returned to the client preserves the on-disk shape verbatim.
type TenantExportNode struct {
	TenantID   string         `json:"tenant_id"`
	NodeID     string         `json:"node_id"`
	TypeID     int32          `json:"type_id"`
	Payload    map[string]any `json:"payload"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
	OwnerActor string         `json:"owner_actor"`
	DataPolicy string         `json:"data_policy"`
}

// TenantExport is the per-tenant slice of the cross-tenant
// ExportUserData bundle.
type TenantExport struct {
	TenantID string             `json:"tenant_id"`
	Nodes    []TenantExportNode `json:"nodes"`
}

// ExportUserData collects every node in `tenantID` that the caller
// owns or is the subject of, excluding `data_policy=audit` types.
//
// `principal` is the per-tenant principal form (`user:<id>`). `reg` is
// the schema registry used for data-policy / subject-field lookups; nil
// is permitted and falls back to DataPolicyPersonal with no subject
// field.
//
// The returned `Nodes` slice is non-nil even when empty — JSON consumers
// expect `[]`, not `null`.
func (s *CanonicalStore) ExportUserData(
	ctx context.Context,
	tenantID, principal string,
	reg *schema.Registry,
) (TenantExport, error) {
	out := TenantExport{TenantID: tenantID, Nodes: []TenantExportNode{}}
	db, err := s.readDB(tenantID)
	if err != nil {
		return out, err
	}
	rows, err := db.QueryContext(ctx, `
		SELECT node_id, type_id, payload_json,
		       created_at, updated_at, owner_actor
		FROM nodes WHERE tenant_id = ?`,
		tenantID,
	)
	if err != nil {
		return out, fmt.Errorf("store: ExportUserData: %w", err)
	}
	defer rows.Close()
	for rows.Next() {
		var (
			nodeID, payloadJSON, owner string
			typeID                     int32
			createdAt, updatedAt       int64
		)
		if err := rows.Scan(&nodeID, &typeID, &payloadJSON, &createdAt, &updatedAt, &owner); err != nil {
			return out, fmt.Errorf("store: ExportUserData scan: %w", err)
		}

		// Schema lookups: missing type → PERSONAL, no subject field.
		// Per ADR-031 the subject field is identified by its field_id; the
		// payload map is keyed by stringified field_id (ADR-018), so the
		// lookup uses the decimal-string id key directly.
		var (
			policy          schema.DataPolicy = schema.DataPolicyPersonal
			subjectFieldID  uint32
			hasSubjectField bool
		)
		if reg != nil {
			if nt := reg.NodeTypeByID(typeID); nt != nil {
				policy = reg.DataPolicyOf(typeID)
				subjectFieldID, hasSubjectField = reg.SubjectFieldID(typeID)
			}
		}

		// AUDIT records are NOT subject-access-requestable (ADR-004).
		if policy == schema.DataPolicyAudit {
			continue
		}

		// Best-effort canonical parse: a malformed payload becomes {}
		// rather than failing the whole export; int64 survives (ADR-028).
		payload, _ := jsonnum.Decode([]byte(payloadJSON))

		isOwner := owner == principal
		isSubject := false
		if hasSubjectField {
			// Strip the `user:` prefix from `principal` before
			// comparing to the subject field value (which stores the
			// bare user_id, e.g. "alice", not the principal form).
			subjectID := principal
			if len(subjectID) > 5 && subjectID[:5] == "user:" {
				subjectID = subjectID[5:]
			}
			key := strconv.FormatUint(uint64(subjectFieldID), 10)
			if v, ok := payload[key]; ok && v == subjectID {
				isSubject = true
			}
		}
		if !(isOwner || isSubject) {
			continue
		}

		out.Nodes = append(out.Nodes, TenantExportNode{
			TenantID:   tenantID,
			NodeID:     nodeID,
			TypeID:     typeID,
			Payload:    payload,
			CreatedAt:  createdAt,
			UpdatedAt:  updatedAt,
			OwnerActor: owner,
			DataPolicy: string(policy),
		})
	}
	if err := rows.Err(); err != nil {
		return out, fmt.Errorf("store: ExportUserData rows: %w", err)
	}
	return out, nil
}

// isUniqueViolation reports whether err is a SQLite UNIQUE-constraint
// failure. modernc.org/sqlite returns errors whose messages contain
// "constraint failed: UNIQUE" — we string-match because the driver does
// not export typed sentinels for these.
func isUniqueViolation(err error) bool {
	if err == nil {
		return false
	}
	msg := err.Error()
	return strings.Contains(msg, "UNIQUE constraint failed") ||
		strings.Contains(msg, "constraint failed: UNIQUE")
}
