// EntDB Console — curated, browser-facing API.
//
// This proto file is the LITERAL access policy for the entdb-console binary.
// Every RPC the browser is allowed to call MUST be declared here. Anything
// not listed is unreachable from the SPA — the ConnectRPC handler has no
// route for it, full stop. This is intentional: the proto is the security
// boundary, not a stylistic choice.
//
// Each RPC reuses the request/response messages from the upstream
// `entdb.v1.EntDBService` proto so each Console handler is a one-line
// pass-through to the upstream gRPC client. Adding a new RPC therefore
// requires touching this file (and getting it through review) rather
// than just exposing whatever the upstream happens to support.
//
// Scope (PR 2): read-only RPCs from PR 1, plus narrow sandbox-only
// CREATE write RPCs (`SandboxCreateNode`, `SandboxCreateEdge`). Writes
// are gated to a single configured sandbox tenant; the console binary
// rejects any other tenant id at the handler. The sandbox RPCs use
// narrow request/response messages defined in this file (NOT
// `entdb.v1.ExecuteAtomicRequest`) so the browser can never construct
// a multi-op transaction or target arbitrary fields outside the
// curated CREATE shape. The handler builds the underlying single-op
// `ExecuteAtomicRequest` itself before forwarding upstream.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: console.proto

package consolev1

import (
	pb "github.com/elloloop/tenant-shard-db/sdk/go/entdb/internal/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SandboxCreateNodeRequest — narrow CREATE shape for the sandbox.
//
// Wire-format invariant: `payload` is keyed by the schema's numeric
// field id (e.g. `{"1": "value"}`), matching the on-disk format used
// by the rest of the system. The frontend does NOT translate
// name-keyed payloads to id-keyed; the user is expected to consult
// the schema page to know what field ids to write. This is a
// debug-tool deliberate non-feature for v1.
type SandboxCreateNodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant id; MUST equal the console's configured sandbox tenant.
	// Rejected with `permission_denied` otherwise.
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Actor performing the write, in `user:<id>` / `system:<name>` form.
	// The handler does NOT fall back to a server-side default — the
	// SPA pre-fills this from `--sandbox-default-actor`, but the wire
	// value is what the upstream sees.
	Actor string `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	// Node type id (numeric, from the schema).
	TypeId int32 `protobuf:"varint,3,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	// Id-keyed payload (see message-level comment).
	Payload *structpb.Struct `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	// Optional idempotency key. Generated upstream if empty.
	IdempotencyKey string `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SandboxCreateNodeRequest) Reset() {
	*x = SandboxCreateNodeRequest{}
	mi := &file_console_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxCreateNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxCreateNodeRequest) ProtoMessage() {}

func (x *SandboxCreateNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxCreateNodeRequest.ProtoReflect.Descriptor instead.
func (*SandboxCreateNodeRequest) Descriptor() ([]byte, []int) {
	return file_console_proto_rawDescGZIP(), []int{0}
}

func (x *SandboxCreateNodeRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SandboxCreateNodeRequest) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *SandboxCreateNodeRequest) GetTypeId() int32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *SandboxCreateNodeRequest) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SandboxCreateNodeRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type SandboxCreateNodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id of the newly created node, as assigned by upstream.
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Idempotency key (echoed from request, or upstream-generated).
	IdempotencyKey string `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// WAL stream position where the create event was written.
	StreamPosition string `protobuf:"bytes,3,opt,name=stream_position,json=streamPosition,proto3" json:"stream_position,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SandboxCreateNodeResponse) Reset() {
	*x = SandboxCreateNodeResponse{}
	mi := &file_console_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxCreateNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxCreateNodeResponse) ProtoMessage() {}

func (x *SandboxCreateNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_console_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxCreateNodeResponse.ProtoReflect.Descriptor instead.
func (*SandboxCreateNodeResponse) Descriptor() ([]byte, []int) {
	return file_console_proto_rawDescGZIP(), []int{1}
}

func (x *SandboxCreateNodeResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SandboxCreateNodeResponse) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *SandboxCreateNodeResponse) GetStreamPosition() string {
	if x != nil {
		return x.StreamPosition
	}
	return ""
}

// SandboxCreateEdgeRequest — narrow CREATE shape for sandbox edges.
//
// `from_node_id` and `to_node_id` are direct node ids (no aliases, no
// cross-op references — that's a multi-op transaction shape we
// deliberately do not expose to the browser).
type SandboxCreateEdgeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant id; MUST equal the console's configured sandbox tenant.
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Actor performing the write.
	Actor string `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	// Edge type id (numeric, from the schema).
	EdgeTypeId int32 `protobuf:"varint,3,opt,name=edge_type_id,json=edgeTypeId,proto3" json:"edge_type_id,omitempty"`
	// Source node id.
	FromNodeId string `protobuf:"bytes,4,opt,name=from_node_id,json=fromNodeId,proto3" json:"from_node_id,omitempty"`
	// Target node id.
	ToNodeId string `protobuf:"bytes,5,opt,name=to_node_id,json=toNodeId,proto3" json:"to_node_id,omitempty"`
	// Optional id-keyed edge properties.
	Props *structpb.Struct `protobuf:"bytes,6,opt,name=props,proto3" json:"props,omitempty"`
	// Optional idempotency key.
	IdempotencyKey string `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SandboxCreateEdgeRequest) Reset() {
	*x = SandboxCreateEdgeRequest{}
	mi := &file_console_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxCreateEdgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxCreateEdgeRequest) ProtoMessage() {}

func (x *SandboxCreateEdgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxCreateEdgeRequest.ProtoReflect.Descriptor instead.
func (*SandboxCreateEdgeRequest) Descriptor() ([]byte, []int) {
	return file_console_proto_rawDescGZIP(), []int{2}
}

func (x *SandboxCreateEdgeRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SandboxCreateEdgeRequest) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *SandboxCreateEdgeRequest) GetEdgeTypeId() int32 {
	if x != nil {
		return x.EdgeTypeId
	}
	return 0
}

func (x *SandboxCreateEdgeRequest) GetFromNodeId() string {
	if x != nil {
		return x.FromNodeId
	}
	return ""
}

func (x *SandboxCreateEdgeRequest) GetToNodeId() string {
	if x != nil {
		return x.ToNodeId
	}
	return ""
}

func (x *SandboxCreateEdgeRequest) GetProps() *structpb.Struct {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *SandboxCreateEdgeRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

// SandboxCreateEdgeResponse — note there is intentionally no
// `edge_id` field. Upstream `ExecuteAtomicResponse` does not surface
// a server-assigned edge id (edges are keyed by `(edge_type_id, from,
// to)` in the canonical store), so there's nothing meaningful to
// return. If a future schema makes edge ids first-class, that's a
// new field at the next field number.
type SandboxCreateEdgeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Idempotency key (echoed or upstream-generated).
	IdempotencyKey string `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// WAL stream position where the create event was written.
	StreamPosition string `protobuf:"bytes,2,opt,name=stream_position,json=streamPosition,proto3" json:"stream_position,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SandboxCreateEdgeResponse) Reset() {
	*x = SandboxCreateEdgeResponse{}
	mi := &file_console_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxCreateEdgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxCreateEdgeResponse) ProtoMessage() {}

func (x *SandboxCreateEdgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_console_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxCreateEdgeResponse.ProtoReflect.Descriptor instead.
func (*SandboxCreateEdgeResponse) Descriptor() ([]byte, []int) {
	return file_console_proto_rawDescGZIP(), []int{3}
}

func (x *SandboxCreateEdgeResponse) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *SandboxCreateEdgeResponse) GetStreamPosition() string {
	if x != nil {
		return x.StreamPosition
	}
	return ""
}

var File_console_proto protoreflect.FileDescriptor

const file_console_proto_rawDesc = "" +
	"\n" +
	"\rconsole.proto\x12\x10entdb.console.v1\x1a\ventdb.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xc2\x01\n" +
	"\x18SandboxCreateNodeRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05actor\x18\x02 \x01(\tR\x05actor\x12\x17\n" +
	"\atype_id\x18\x03 \x01(\x05R\x06typeId\x121\n" +
	"\apayload\x18\x04 \x01(\v2\x17.google.protobuf.StructR\apayload\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"\x86\x01\n" +
	"\x19SandboxCreateNodeResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12'\n" +
	"\x0fstream_position\x18\x03 \x01(\tR\x0estreamPosition\"\x87\x02\n" +
	"\x18SandboxCreateEdgeRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05actor\x18\x02 \x01(\tR\x05actor\x12 \n" +
	"\fedge_type_id\x18\x03 \x01(\x05R\n" +
	"edgeTypeId\x12 \n" +
	"\ffrom_node_id\x18\x04 \x01(\tR\n" +
	"fromNodeId\x12\x1c\n" +
	"\n" +
	"to_node_id\x18\x05 \x01(\tR\btoNodeId\x12-\n" +
	"\x05props\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x05props\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKey\"m\n" +
	"\x19SandboxCreateEdgeResponse\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12'\n" +
	"\x0fstream_position\x18\x02 \x01(\tR\x0estreamPosition2\xbf\a\n" +
	"\aConsole\x12;\n" +
	"\x06Health\x12\x17.entdb.v1.HealthRequest\x1a\x18.entdb.v1.HealthResponse\x12J\n" +
	"\vListTenants\x12\x1c.entdb.v1.ListTenantsRequest\x1a\x1d.entdb.v1.ListTenantsResponse\x12D\n" +
	"\tGetTenant\x12\x1a.entdb.v1.GetTenantRequest\x1a\x1b.entdb.v1.GetTenantResponse\x12D\n" +
	"\tGetSchema\x12\x1a.entdb.v1.GetSchemaRequest\x1a\x1b.entdb.v1.GetSchemaResponse\x12G\n" +
	"\n" +
	"QueryNodes\x12\x1b.entdb.v1.QueryNodesRequest\x1a\x1c.entdb.v1.QueryNodesResponse\x12>\n" +
	"\aGetNode\x12\x18.entdb.v1.GetNodeRequest\x1a\x19.entdb.v1.GetNodeResponse\x12E\n" +
	"\fGetEdgesFrom\x12\x19.entdb.v1.GetEdgesRequest\x1a\x1a.entdb.v1.GetEdgesResponse\x12C\n" +
	"\n" +
	"GetEdgesTo\x12\x19.entdb.v1.GetEdgesRequest\x1a\x1a.entdb.v1.GetEdgesResponse\x12\\\n" +
	"\x11GetConnectedNodes\x12\".entdb.v1.GetConnectedNodesRequest\x1a#.entdb.v1.GetConnectedNodesResponse\x12P\n" +
	"\rSearchMailbox\x12\x1e.entdb.v1.SearchMailboxRequest\x1a\x1f.entdb.v1.SearchMailboxResponse\x12l\n" +
	"\x11SandboxCreateNode\x12*.entdb.console.v1.SandboxCreateNodeRequest\x1a+.entdb.console.v1.SandboxCreateNodeResponse\x12l\n" +
	"\x11SandboxCreateEdge\x12*.entdb.console.v1.SandboxCreateEdgeRequest\x1a+.entdb.console.v1.SandboxCreateEdgeResponseBPZNgithub.com/elloloop/tenant-shard-db/sdk/go/entdb/internal/console/v1;consolev1b\x06proto3"

var (
	file_console_proto_rawDescOnce sync.Once
	file_console_proto_rawDescData []byte
)

func file_console_proto_rawDescGZIP() []byte {
	file_console_proto_rawDescOnce.Do(func() {
		file_console_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_console_proto_rawDesc), len(file_console_proto_rawDesc)))
	})
	return file_console_proto_rawDescData
}

var file_console_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_console_proto_goTypes = []any{
	(*SandboxCreateNodeRequest)(nil),     // 0: entdb.console.v1.SandboxCreateNodeRequest
	(*SandboxCreateNodeResponse)(nil),    // 1: entdb.console.v1.SandboxCreateNodeResponse
	(*SandboxCreateEdgeRequest)(nil),     // 2: entdb.console.v1.SandboxCreateEdgeRequest
	(*SandboxCreateEdgeResponse)(nil),    // 3: entdb.console.v1.SandboxCreateEdgeResponse
	(*structpb.Struct)(nil),              // 4: google.protobuf.Struct
	(*pb.HealthRequest)(nil),             // 5: entdb.v1.HealthRequest
	(*pb.ListTenantsRequest)(nil),        // 6: entdb.v1.ListTenantsRequest
	(*pb.GetTenantRequest)(nil),          // 7: entdb.v1.GetTenantRequest
	(*pb.GetSchemaRequest)(nil),          // 8: entdb.v1.GetSchemaRequest
	(*pb.QueryNodesRequest)(nil),         // 9: entdb.v1.QueryNodesRequest
	(*pb.GetNodeRequest)(nil),            // 10: entdb.v1.GetNodeRequest
	(*pb.GetEdgesRequest)(nil),           // 11: entdb.v1.GetEdgesRequest
	(*pb.GetConnectedNodesRequest)(nil),  // 12: entdb.v1.GetConnectedNodesRequest
	(*pb.SearchMailboxRequest)(nil),      // 13: entdb.v1.SearchMailboxRequest
	(*pb.HealthResponse)(nil),            // 14: entdb.v1.HealthResponse
	(*pb.ListTenantsResponse)(nil),       // 15: entdb.v1.ListTenantsResponse
	(*pb.GetTenantResponse)(nil),         // 16: entdb.v1.GetTenantResponse
	(*pb.GetSchemaResponse)(nil),         // 17: entdb.v1.GetSchemaResponse
	(*pb.QueryNodesResponse)(nil),        // 18: entdb.v1.QueryNodesResponse
	(*pb.GetNodeResponse)(nil),           // 19: entdb.v1.GetNodeResponse
	(*pb.GetEdgesResponse)(nil),          // 20: entdb.v1.GetEdgesResponse
	(*pb.GetConnectedNodesResponse)(nil), // 21: entdb.v1.GetConnectedNodesResponse
	(*pb.SearchMailboxResponse)(nil),     // 22: entdb.v1.SearchMailboxResponse
}
var file_console_proto_depIdxs = []int32{
	4,  // 0: entdb.console.v1.SandboxCreateNodeRequest.payload:type_name -> google.protobuf.Struct
	4,  // 1: entdb.console.v1.SandboxCreateEdgeRequest.props:type_name -> google.protobuf.Struct
	5,  // 2: entdb.console.v1.Console.Health:input_type -> entdb.v1.HealthRequest
	6,  // 3: entdb.console.v1.Console.ListTenants:input_type -> entdb.v1.ListTenantsRequest
	7,  // 4: entdb.console.v1.Console.GetTenant:input_type -> entdb.v1.GetTenantRequest
	8,  // 5: entdb.console.v1.Console.GetSchema:input_type -> entdb.v1.GetSchemaRequest
	9,  // 6: entdb.console.v1.Console.QueryNodes:input_type -> entdb.v1.QueryNodesRequest
	10, // 7: entdb.console.v1.Console.GetNode:input_type -> entdb.v1.GetNodeRequest
	11, // 8: entdb.console.v1.Console.GetEdgesFrom:input_type -> entdb.v1.GetEdgesRequest
	11, // 9: entdb.console.v1.Console.GetEdgesTo:input_type -> entdb.v1.GetEdgesRequest
	12, // 10: entdb.console.v1.Console.GetConnectedNodes:input_type -> entdb.v1.GetConnectedNodesRequest
	13, // 11: entdb.console.v1.Console.SearchMailbox:input_type -> entdb.v1.SearchMailboxRequest
	0,  // 12: entdb.console.v1.Console.SandboxCreateNode:input_type -> entdb.console.v1.SandboxCreateNodeRequest
	2,  // 13: entdb.console.v1.Console.SandboxCreateEdge:input_type -> entdb.console.v1.SandboxCreateEdgeRequest
	14, // 14: entdb.console.v1.Console.Health:output_type -> entdb.v1.HealthResponse
	15, // 15: entdb.console.v1.Console.ListTenants:output_type -> entdb.v1.ListTenantsResponse
	16, // 16: entdb.console.v1.Console.GetTenant:output_type -> entdb.v1.GetTenantResponse
	17, // 17: entdb.console.v1.Console.GetSchema:output_type -> entdb.v1.GetSchemaResponse
	18, // 18: entdb.console.v1.Console.QueryNodes:output_type -> entdb.v1.QueryNodesResponse
	19, // 19: entdb.console.v1.Console.GetNode:output_type -> entdb.v1.GetNodeResponse
	20, // 20: entdb.console.v1.Console.GetEdgesFrom:output_type -> entdb.v1.GetEdgesResponse
	20, // 21: entdb.console.v1.Console.GetEdgesTo:output_type -> entdb.v1.GetEdgesResponse
	21, // 22: entdb.console.v1.Console.GetConnectedNodes:output_type -> entdb.v1.GetConnectedNodesResponse
	22, // 23: entdb.console.v1.Console.SearchMailbox:output_type -> entdb.v1.SearchMailboxResponse
	1,  // 24: entdb.console.v1.Console.SandboxCreateNode:output_type -> entdb.console.v1.SandboxCreateNodeResponse
	3,  // 25: entdb.console.v1.Console.SandboxCreateEdge:output_type -> entdb.console.v1.SandboxCreateEdgeResponse
	14, // [14:26] is the sub-list for method output_type
	2,  // [2:14] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_console_proto_init() }
func file_console_proto_init() {
	if File_console_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_console_proto_rawDesc), len(file_console_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_console_proto_goTypes,
		DependencyIndexes: file_console_proto_depIdxs,
		MessageInfos:      file_console_proto_msgTypes,
	}.Build()
	File_console_proto = out.File
	file_console_proto_goTypes = nil
	file_console_proto_depIdxs = nil
}
