// EntDB Console — curated, browser-facing API.
//
// This proto file is the LITERAL access policy for the entdb-console binary.
// Every RPC the browser is allowed to call MUST be declared here. Anything
// not listed is unreachable from the SPA — the ConnectRPC handler has no
// route for it, full stop. This is intentional: the proto is the security
// boundary, not a stylistic choice.
//
// Each RPC reuses the request/response messages from the upstream
// `entdb.v1.EntDBService` proto so each Console handler is a one-line
// pass-through to the upstream gRPC client. Adding a new RPC therefore
// requires touching this file (and getting it through review) rather
// than just exposing whatever the upstream happens to support.
//
// Scope (PR 1): READ-ONLY RPCs only. Sandbox writes ship in PR 2.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: console.proto

package consolev1

import (
	pb "github.com/elloloop/tenant-shard-db/sdk/go/entdb/internal/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_console_proto protoreflect.FileDescriptor

const file_console_proto_rawDesc = "" +
	"\n" +
	"\rconsole.proto\x12\x10entdb.console.v1\x1a\ventdb.proto2\xe3\x05\n" +
	"\aConsole\x12;\n" +
	"\x06Health\x12\x17.entdb.v1.HealthRequest\x1a\x18.entdb.v1.HealthResponse\x12J\n" +
	"\vListTenants\x12\x1c.entdb.v1.ListTenantsRequest\x1a\x1d.entdb.v1.ListTenantsResponse\x12D\n" +
	"\tGetTenant\x12\x1a.entdb.v1.GetTenantRequest\x1a\x1b.entdb.v1.GetTenantResponse\x12D\n" +
	"\tGetSchema\x12\x1a.entdb.v1.GetSchemaRequest\x1a\x1b.entdb.v1.GetSchemaResponse\x12G\n" +
	"\n" +
	"QueryNodes\x12\x1b.entdb.v1.QueryNodesRequest\x1a\x1c.entdb.v1.QueryNodesResponse\x12>\n" +
	"\aGetNode\x12\x18.entdb.v1.GetNodeRequest\x1a\x19.entdb.v1.GetNodeResponse\x12E\n" +
	"\fGetEdgesFrom\x12\x19.entdb.v1.GetEdgesRequest\x1a\x1a.entdb.v1.GetEdgesResponse\x12C\n" +
	"\n" +
	"GetEdgesTo\x12\x19.entdb.v1.GetEdgesRequest\x1a\x1a.entdb.v1.GetEdgesResponse\x12\\\n" +
	"\x11GetConnectedNodes\x12\".entdb.v1.GetConnectedNodesRequest\x1a#.entdb.v1.GetConnectedNodesResponse\x12P\n" +
	"\rSearchMailbox\x12\x1e.entdb.v1.SearchMailboxRequest\x1a\x1f.entdb.v1.SearchMailboxResponseBPZNgithub.com/elloloop/tenant-shard-db/sdk/go/entdb/internal/console/v1;consolev1b\x06proto3"

var file_console_proto_goTypes = []any{
	(*pb.HealthRequest)(nil),             // 0: entdb.v1.HealthRequest
	(*pb.ListTenantsRequest)(nil),        // 1: entdb.v1.ListTenantsRequest
	(*pb.GetTenantRequest)(nil),          // 2: entdb.v1.GetTenantRequest
	(*pb.GetSchemaRequest)(nil),          // 3: entdb.v1.GetSchemaRequest
	(*pb.QueryNodesRequest)(nil),         // 4: entdb.v1.QueryNodesRequest
	(*pb.GetNodeRequest)(nil),            // 5: entdb.v1.GetNodeRequest
	(*pb.GetEdgesRequest)(nil),           // 6: entdb.v1.GetEdgesRequest
	(*pb.GetConnectedNodesRequest)(nil),  // 7: entdb.v1.GetConnectedNodesRequest
	(*pb.SearchMailboxRequest)(nil),      // 8: entdb.v1.SearchMailboxRequest
	(*pb.HealthResponse)(nil),            // 9: entdb.v1.HealthResponse
	(*pb.ListTenantsResponse)(nil),       // 10: entdb.v1.ListTenantsResponse
	(*pb.GetTenantResponse)(nil),         // 11: entdb.v1.GetTenantResponse
	(*pb.GetSchemaResponse)(nil),         // 12: entdb.v1.GetSchemaResponse
	(*pb.QueryNodesResponse)(nil),        // 13: entdb.v1.QueryNodesResponse
	(*pb.GetNodeResponse)(nil),           // 14: entdb.v1.GetNodeResponse
	(*pb.GetEdgesResponse)(nil),          // 15: entdb.v1.GetEdgesResponse
	(*pb.GetConnectedNodesResponse)(nil), // 16: entdb.v1.GetConnectedNodesResponse
	(*pb.SearchMailboxResponse)(nil),     // 17: entdb.v1.SearchMailboxResponse
}
var file_console_proto_depIdxs = []int32{
	0,  // 0: entdb.console.v1.Console.Health:input_type -> entdb.v1.HealthRequest
	1,  // 1: entdb.console.v1.Console.ListTenants:input_type -> entdb.v1.ListTenantsRequest
	2,  // 2: entdb.console.v1.Console.GetTenant:input_type -> entdb.v1.GetTenantRequest
	3,  // 3: entdb.console.v1.Console.GetSchema:input_type -> entdb.v1.GetSchemaRequest
	4,  // 4: entdb.console.v1.Console.QueryNodes:input_type -> entdb.v1.QueryNodesRequest
	5,  // 5: entdb.console.v1.Console.GetNode:input_type -> entdb.v1.GetNodeRequest
	6,  // 6: entdb.console.v1.Console.GetEdgesFrom:input_type -> entdb.v1.GetEdgesRequest
	6,  // 7: entdb.console.v1.Console.GetEdgesTo:input_type -> entdb.v1.GetEdgesRequest
	7,  // 8: entdb.console.v1.Console.GetConnectedNodes:input_type -> entdb.v1.GetConnectedNodesRequest
	8,  // 9: entdb.console.v1.Console.SearchMailbox:input_type -> entdb.v1.SearchMailboxRequest
	9,  // 10: entdb.console.v1.Console.Health:output_type -> entdb.v1.HealthResponse
	10, // 11: entdb.console.v1.Console.ListTenants:output_type -> entdb.v1.ListTenantsResponse
	11, // 12: entdb.console.v1.Console.GetTenant:output_type -> entdb.v1.GetTenantResponse
	12, // 13: entdb.console.v1.Console.GetSchema:output_type -> entdb.v1.GetSchemaResponse
	13, // 14: entdb.console.v1.Console.QueryNodes:output_type -> entdb.v1.QueryNodesResponse
	14, // 15: entdb.console.v1.Console.GetNode:output_type -> entdb.v1.GetNodeResponse
	15, // 16: entdb.console.v1.Console.GetEdgesFrom:output_type -> entdb.v1.GetEdgesResponse
	15, // 17: entdb.console.v1.Console.GetEdgesTo:output_type -> entdb.v1.GetEdgesResponse
	16, // 18: entdb.console.v1.Console.GetConnectedNodes:output_type -> entdb.v1.GetConnectedNodesResponse
	17, // 19: entdb.console.v1.Console.SearchMailbox:output_type -> entdb.v1.SearchMailboxResponse
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_console_proto_init() }
func file_console_proto_init() {
	if File_console_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_console_proto_rawDesc), len(file_console_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_console_proto_goTypes,
		DependencyIndexes: file_console_proto_depIdxs,
	}.Build()
	File_console_proto = out.File
	file_console_proto_goTypes = nil
	file_console_proto_depIdxs = nil
}
