"""Typed node base class for generated EntDB schema wrappers.

Subclasses are generated by ``codegen.generate_python`` and provide
typed dataclass access with ``to_payload`` / ``from_payload`` helpers.

Example (generated code)::

    @dataclass
    class Task(TypedNode):
        title: str
        status: str
        assignee_id: str | None = None

        _type_id: ClassVar[int] = 101
        _type_name: ClassVar[str] = "Task"
"""

from __future__ import annotations

import dataclasses
from typing import Any, ClassVar


@dataclasses.dataclass
class TypedNode:
    """Base class for generated typed node wrappers.

    Subclasses declare their fields as regular dataclass fields and set
    ``_type_id`` and ``_type_name`` class variables.
    """

    _type_id: ClassVar[int] = 0
    _type_name: ClassVar[str] = ""

    def to_payload(self) -> dict[str, Any]:
        """Convert dataclass fields to a payload dictionary.

        Only includes fields that are not ``None``, matching the
        sparse-payload convention used by EntDB writes.
        """
        result: dict[str, Any] = {}
        for f in dataclasses.fields(self):
            value = getattr(self, f.name)
            if value is not None:
                result[f.name] = value
        return result

    @classmethod
    def from_payload(cls, payload: dict[str, Any]) -> TypedNode:
        """Construct an instance from a payload dictionary.

        Unknown keys in ``payload`` are silently ignored so that
        forward-compatible payloads (with fields not yet in the
        generated code) do not raise.
        """
        known = {f.name for f in dataclasses.fields(cls)}
        filtered = {k: v for k, v in payload.items() if k in known}
        return cls(**filtered)
