// EntDB gRPC Service Definition
//
// This file defines the gRPC API for the EntDB database service.
// The API supports node/edge graph operations with tenant isolation.
//
// Key concepts:
// - Every operation requires tenant_id and actor
// - Writes are atomic via ExecuteAtomic RPC
// - Reads are eventually consistent from SQLite views
//
// Compatibility rules:
// - Field numbers are immutable
// - New fields should be optional
// - Deprecated fields should be marked but kept

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: entdb.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EntDBService_ExecuteAtomic_FullMethodName       = "/entdb.v1.EntDBService/ExecuteAtomic"
	EntDBService_GetReceiptStatus_FullMethodName    = "/entdb.v1.EntDBService/GetReceiptStatus"
	EntDBService_GetNode_FullMethodName             = "/entdb.v1.EntDBService/GetNode"
	EntDBService_GetNodes_FullMethodName            = "/entdb.v1.EntDBService/GetNodes"
	EntDBService_QueryNodes_FullMethodName          = "/entdb.v1.EntDBService/QueryNodes"
	EntDBService_GetEdgesFrom_FullMethodName        = "/entdb.v1.EntDBService/GetEdgesFrom"
	EntDBService_GetEdgesTo_FullMethodName          = "/entdb.v1.EntDBService/GetEdgesTo"
	EntDBService_SearchMailbox_FullMethodName       = "/entdb.v1.EntDBService/SearchMailbox"
	EntDBService_GetMailbox_FullMethodName          = "/entdb.v1.EntDBService/GetMailbox"
	EntDBService_Health_FullMethodName              = "/entdb.v1.EntDBService/Health"
	EntDBService_GetSchema_FullMethodName           = "/entdb.v1.EntDBService/GetSchema"
	EntDBService_ListTenants_FullMethodName         = "/entdb.v1.EntDBService/ListTenants"
	EntDBService_ListMailboxUsers_FullMethodName    = "/entdb.v1.EntDBService/ListMailboxUsers"
	EntDBService_WaitForOffset_FullMethodName       = "/entdb.v1.EntDBService/WaitForOffset"
	EntDBService_GetConnectedNodes_FullMethodName   = "/entdb.v1.EntDBService/GetConnectedNodes"
	EntDBService_ShareNode_FullMethodName           = "/entdb.v1.EntDBService/ShareNode"
	EntDBService_RevokeAccess_FullMethodName        = "/entdb.v1.EntDBService/RevokeAccess"
	EntDBService_ListSharedWithMe_FullMethodName    = "/entdb.v1.EntDBService/ListSharedWithMe"
	EntDBService_AddGroupMember_FullMethodName      = "/entdb.v1.EntDBService/AddGroupMember"
	EntDBService_RemoveGroupMember_FullMethodName   = "/entdb.v1.EntDBService/RemoveGroupMember"
	EntDBService_TransferOwnership_FullMethodName   = "/entdb.v1.EntDBService/TransferOwnership"
	EntDBService_CreateUser_FullMethodName          = "/entdb.v1.EntDBService/CreateUser"
	EntDBService_GetUser_FullMethodName             = "/entdb.v1.EntDBService/GetUser"
	EntDBService_UpdateUser_FullMethodName          = "/entdb.v1.EntDBService/UpdateUser"
	EntDBService_ListUsers_FullMethodName           = "/entdb.v1.EntDBService/ListUsers"
	EntDBService_CreateTenant_FullMethodName        = "/entdb.v1.EntDBService/CreateTenant"
	EntDBService_GetTenant_FullMethodName           = "/entdb.v1.EntDBService/GetTenant"
	EntDBService_ArchiveTenant_FullMethodName       = "/entdb.v1.EntDBService/ArchiveTenant"
	EntDBService_AddTenantMember_FullMethodName     = "/entdb.v1.EntDBService/AddTenantMember"
	EntDBService_RemoveTenantMember_FullMethodName  = "/entdb.v1.EntDBService/RemoveTenantMember"
	EntDBService_GetTenantMembers_FullMethodName    = "/entdb.v1.EntDBService/GetTenantMembers"
	EntDBService_GetUserTenants_FullMethodName      = "/entdb.v1.EntDBService/GetUserTenants"
	EntDBService_ChangeMemberRole_FullMethodName    = "/entdb.v1.EntDBService/ChangeMemberRole"
	EntDBService_TransferUserContent_FullMethodName = "/entdb.v1.EntDBService/TransferUserContent"
	EntDBService_DelegateAccess_FullMethodName      = "/entdb.v1.EntDBService/DelegateAccess"
	EntDBService_SetLegalHold_FullMethodName        = "/entdb.v1.EntDBService/SetLegalHold"
	EntDBService_RevokeAllUserAccess_FullMethodName = "/entdb.v1.EntDBService/RevokeAllUserAccess"
	EntDBService_DeleteUser_FullMethodName          = "/entdb.v1.EntDBService/DeleteUser"
	EntDBService_ExportUserData_FullMethodName      = "/entdb.v1.EntDBService/ExportUserData"
	EntDBService_FreezeUser_FullMethodName          = "/entdb.v1.EntDBService/FreezeUser"
	EntDBService_CancelUserDeletion_FullMethodName  = "/entdb.v1.EntDBService/CancelUserDeletion"
	EntDBService_GetTenantQuota_FullMethodName      = "/entdb.v1.EntDBService/GetTenantQuota"
	EntDBService_GetNodeByKey_FullMethodName        = "/entdb.v1.EntDBService/GetNodeByKey"
	EntDBService_SearchNodes_FullMethodName         = "/entdb.v1.EntDBService/SearchNodes"
)

// EntDBServiceClient is the client API for EntDBService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EntDB Service - Main API for database operations
type EntDBServiceClient interface {
	// Execute an atomic transaction containing one or more operations
	// Returns a receipt that can be used to check application status
	ExecuteAtomic(ctx context.Context, in *ExecuteAtomicRequest, opts ...grpc.CallOption) (*ExecuteAtomicResponse, error)
	// Get the status of a previously submitted transaction
	GetReceiptStatus(ctx context.Context, in *GetReceiptStatusRequest, opts ...grpc.CallOption) (*GetReceiptStatusResponse, error)
	// Get a node by ID
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error)
	// Get multiple nodes by IDs
	GetNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (*GetNodesResponse, error)
	// Query nodes by type with optional filters
	QueryNodes(ctx context.Context, in *QueryNodesRequest, opts ...grpc.CallOption) (*QueryNodesResponse, error)
	// Get outgoing edges from a node
	GetEdgesFrom(ctx context.Context, in *GetEdgesRequest, opts ...grpc.CallOption) (*GetEdgesResponse, error)
	// Get incoming edges to a node
	GetEdgesTo(ctx context.Context, in *GetEdgesRequest, opts ...grpc.CallOption) (*GetEdgesResponse, error)
	// Search mailbox with full-text search
	SearchMailbox(ctx context.Context, in *SearchMailboxRequest, opts ...grpc.CallOption) (*SearchMailboxResponse, error)
	// Get mailbox items for a user
	GetMailbox(ctx context.Context, in *GetMailboxRequest, opts ...grpc.CallOption) (*GetMailboxResponse, error)
	// Get server health and status
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Get schema information
	GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error)
	// List all tenants that have data
	ListTenants(ctx context.Context, in *ListTenantsRequest, opts ...grpc.CallOption) (*ListTenantsResponse, error)
	// List mailbox users for a tenant
	ListMailboxUsers(ctx context.Context, in *ListMailboxUsersRequest, opts ...grpc.CallOption) (*ListMailboxUsersResponse, error)
	// Wait for a specific stream position to be applied
	WaitForOffset(ctx context.Context, in *WaitForOffsetRequest, opts ...grpc.CallOption) (*WaitForOffsetResponse, error)
	// ACL v2 - Get connected nodes with ACL filtering
	GetConnectedNodes(ctx context.Context, in *GetConnectedNodesRequest, opts ...grpc.CallOption) (*GetConnectedNodesResponse, error)
	// ACL v2 - Share a node with an actor
	ShareNode(ctx context.Context, in *ShareNodeRequest, opts ...grpc.CallOption) (*ShareNodeResponse, error)
	// ACL v2 - Revoke access from an actor
	RevokeAccess(ctx context.Context, in *RevokeAccessRequest, opts ...grpc.CallOption) (*RevokeAccessResponse, error)
	// ACL v2 - List nodes shared with the caller
	ListSharedWithMe(ctx context.Context, in *ListSharedWithMeRequest, opts ...grpc.CallOption) (*ListSharedWithMeResponse, error)
	// ACL v2 - Add a member to a group
	AddGroupMember(ctx context.Context, in *GroupMemberRequest, opts ...grpc.CallOption) (*GroupMemberResponse, error)
	// ACL v2 - Remove a member from a group
	RemoveGroupMember(ctx context.Context, in *GroupMemberRequest, opts ...grpc.CallOption) (*GroupMemberResponse, error)
	// ACL v2 - Transfer ownership of a node
	TransferOwnership(ctx context.Context, in *TransferOwnershipRequest, opts ...grpc.CallOption) (*TransferOwnershipResponse, error)
	// User registry CRUD
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	// Tenant registry CRUD
	CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*CreateTenantResponse, error)
	GetTenant(ctx context.Context, in *GetTenantRequest, opts ...grpc.CallOption) (*GetTenantResponse, error)
	ArchiveTenant(ctx context.Context, in *ArchiveTenantRequest, opts ...grpc.CallOption) (*ArchiveTenantResponse, error)
	// Tenant membership management
	AddTenantMember(ctx context.Context, in *TenantMemberRequest, opts ...grpc.CallOption) (*TenantMemberResponse, error)
	RemoveTenantMember(ctx context.Context, in *TenantMemberRequest, opts ...grpc.CallOption) (*TenantMemberResponse, error)
	GetTenantMembers(ctx context.Context, in *GetTenantMembersRequest, opts ...grpc.CallOption) (*GetTenantMembersResponse, error)
	GetUserTenants(ctx context.Context, in *GetUserTenantsRequest, opts ...grpc.CallOption) (*GetUserTenantsResponse, error)
	ChangeMemberRole(ctx context.Context, in *ChangeMemberRoleRequest, opts ...grpc.CallOption) (*ChangeMemberRoleResponse, error)
	// Admin operations (Issue #90, ADR-003)
	TransferUserContent(ctx context.Context, in *TransferUserContentRequest, opts ...grpc.CallOption) (*TransferUserContentResponse, error)
	DelegateAccess(ctx context.Context, in *DelegateAccessRequest, opts ...grpc.CallOption) (*DelegateAccessResponse, error)
	SetLegalHold(ctx context.Context, in *LegalHoldRequest, opts ...grpc.CallOption) (*LegalHoldResponse, error)
	RevokeAllUserAccess(ctx context.Context, in *RevokeAllUserAccessRequest, opts ...grpc.CallOption) (*RevokeAllUserAccessResponse, error)
	// GDPR operations (Issue #103, ADR-004)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	ExportUserData(ctx context.Context, in *ExportUserDataRequest, opts ...grpc.CallOption) (*ExportUserDataResponse, error)
	FreezeUser(ctx context.Context, in *FreezeUserRequest, opts ...grpc.CallOption) (*FreezeUserResponse, error)
	CancelUserDeletion(ctx context.Context, in *CancelUserDeletionRequest, opts ...grpc.CallOption) (*CancelUserDeletionResponse, error)
	// Quota dashboard (ADR: docs/decisions/quotas.md)
	GetTenantQuota(ctx context.Context, in *GetTenantQuotaRequest, opts ...grpc.CallOption) (*GetTenantQuotaResponse, error)
	// Unique-key secondary lookup (2026-04-13 unique_keys decision)
	GetNodeByKey(ctx context.Context, in *GetNodeByKeyRequest, opts ...grpc.CallOption) (*GetNodeByKeyResponse, error)
	// Full-text search across searchable fields (2026-04-19 FTS decision)
	SearchNodes(ctx context.Context, in *SearchNodesRequest, opts ...grpc.CallOption) (*SearchNodesResponse, error)
}

type entDBServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEntDBServiceClient(cc grpc.ClientConnInterface) EntDBServiceClient {
	return &entDBServiceClient{cc}
}

func (c *entDBServiceClient) ExecuteAtomic(ctx context.Context, in *ExecuteAtomicRequest, opts ...grpc.CallOption) (*ExecuteAtomicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteAtomicResponse)
	err := c.cc.Invoke(ctx, EntDBService_ExecuteAtomic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) GetReceiptStatus(ctx context.Context, in *GetReceiptStatusRequest, opts ...grpc.CallOption) (*GetReceiptStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReceiptStatusResponse)
	err := c.cc.Invoke(ctx, EntDBService_GetReceiptStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeResponse)
	err := c.cc.Invoke(ctx, EntDBService_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) GetNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (*GetNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodesResponse)
	err := c.cc.Invoke(ctx, EntDBService_GetNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) QueryNodes(ctx context.Context, in *QueryNodesRequest, opts ...grpc.CallOption) (*QueryNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryNodesResponse)
	err := c.cc.Invoke(ctx, EntDBService_QueryNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) GetEdgesFrom(ctx context.Context, in *GetEdgesRequest, opts ...grpc.CallOption) (*GetEdgesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEdgesResponse)
	err := c.cc.Invoke(ctx, EntDBService_GetEdgesFrom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) GetEdgesTo(ctx context.Context, in *GetEdgesRequest, opts ...grpc.CallOption) (*GetEdgesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEdgesResponse)
	err := c.cc.Invoke(ctx, EntDBService_GetEdgesTo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) SearchMailbox(ctx context.Context, in *SearchMailboxRequest, opts ...grpc.CallOption) (*SearchMailboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchMailboxResponse)
	err := c.cc.Invoke(ctx, EntDBService_SearchMailbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) GetMailbox(ctx context.Context, in *GetMailboxRequest, opts ...grpc.CallOption) (*GetMailboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMailboxResponse)
	err := c.cc.Invoke(ctx, EntDBService_GetMailbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, EntDBService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSchemaResponse)
	err := c.cc.Invoke(ctx, EntDBService_GetSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) ListTenants(ctx context.Context, in *ListTenantsRequest, opts ...grpc.CallOption) (*ListTenantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTenantsResponse)
	err := c.cc.Invoke(ctx, EntDBService_ListTenants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) ListMailboxUsers(ctx context.Context, in *ListMailboxUsersRequest, opts ...grpc.CallOption) (*ListMailboxUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMailboxUsersResponse)
	err := c.cc.Invoke(ctx, EntDBService_ListMailboxUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) WaitForOffset(ctx context.Context, in *WaitForOffsetRequest, opts ...grpc.CallOption) (*WaitForOffsetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WaitForOffsetResponse)
	err := c.cc.Invoke(ctx, EntDBService_WaitForOffset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) GetConnectedNodes(ctx context.Context, in *GetConnectedNodesRequest, opts ...grpc.CallOption) (*GetConnectedNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConnectedNodesResponse)
	err := c.cc.Invoke(ctx, EntDBService_GetConnectedNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) ShareNode(ctx context.Context, in *ShareNodeRequest, opts ...grpc.CallOption) (*ShareNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShareNodeResponse)
	err := c.cc.Invoke(ctx, EntDBService_ShareNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) RevokeAccess(ctx context.Context, in *RevokeAccessRequest, opts ...grpc.CallOption) (*RevokeAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeAccessResponse)
	err := c.cc.Invoke(ctx, EntDBService_RevokeAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) ListSharedWithMe(ctx context.Context, in *ListSharedWithMeRequest, opts ...grpc.CallOption) (*ListSharedWithMeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSharedWithMeResponse)
	err := c.cc.Invoke(ctx, EntDBService_ListSharedWithMe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) AddGroupMember(ctx context.Context, in *GroupMemberRequest, opts ...grpc.CallOption) (*GroupMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupMemberResponse)
	err := c.cc.Invoke(ctx, EntDBService_AddGroupMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) RemoveGroupMember(ctx context.Context, in *GroupMemberRequest, opts ...grpc.CallOption) (*GroupMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupMemberResponse)
	err := c.cc.Invoke(ctx, EntDBService_RemoveGroupMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) TransferOwnership(ctx context.Context, in *TransferOwnershipRequest, opts ...grpc.CallOption) (*TransferOwnershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferOwnershipResponse)
	err := c.cc.Invoke(ctx, EntDBService_TransferOwnership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, EntDBService_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, EntDBService_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, EntDBService_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, EntDBService_ListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*CreateTenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTenantResponse)
	err := c.cc.Invoke(ctx, EntDBService_CreateTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) GetTenant(ctx context.Context, in *GetTenantRequest, opts ...grpc.CallOption) (*GetTenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTenantResponse)
	err := c.cc.Invoke(ctx, EntDBService_GetTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) ArchiveTenant(ctx context.Context, in *ArchiveTenantRequest, opts ...grpc.CallOption) (*ArchiveTenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArchiveTenantResponse)
	err := c.cc.Invoke(ctx, EntDBService_ArchiveTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) AddTenantMember(ctx context.Context, in *TenantMemberRequest, opts ...grpc.CallOption) (*TenantMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantMemberResponse)
	err := c.cc.Invoke(ctx, EntDBService_AddTenantMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) RemoveTenantMember(ctx context.Context, in *TenantMemberRequest, opts ...grpc.CallOption) (*TenantMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantMemberResponse)
	err := c.cc.Invoke(ctx, EntDBService_RemoveTenantMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) GetTenantMembers(ctx context.Context, in *GetTenantMembersRequest, opts ...grpc.CallOption) (*GetTenantMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTenantMembersResponse)
	err := c.cc.Invoke(ctx, EntDBService_GetTenantMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) GetUserTenants(ctx context.Context, in *GetUserTenantsRequest, opts ...grpc.CallOption) (*GetUserTenantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserTenantsResponse)
	err := c.cc.Invoke(ctx, EntDBService_GetUserTenants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) ChangeMemberRole(ctx context.Context, in *ChangeMemberRoleRequest, opts ...grpc.CallOption) (*ChangeMemberRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeMemberRoleResponse)
	err := c.cc.Invoke(ctx, EntDBService_ChangeMemberRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) TransferUserContent(ctx context.Context, in *TransferUserContentRequest, opts ...grpc.CallOption) (*TransferUserContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferUserContentResponse)
	err := c.cc.Invoke(ctx, EntDBService_TransferUserContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) DelegateAccess(ctx context.Context, in *DelegateAccessRequest, opts ...grpc.CallOption) (*DelegateAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelegateAccessResponse)
	err := c.cc.Invoke(ctx, EntDBService_DelegateAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) SetLegalHold(ctx context.Context, in *LegalHoldRequest, opts ...grpc.CallOption) (*LegalHoldResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LegalHoldResponse)
	err := c.cc.Invoke(ctx, EntDBService_SetLegalHold_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) RevokeAllUserAccess(ctx context.Context, in *RevokeAllUserAccessRequest, opts ...grpc.CallOption) (*RevokeAllUserAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeAllUserAccessResponse)
	err := c.cc.Invoke(ctx, EntDBService_RevokeAllUserAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, EntDBService_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) ExportUserData(ctx context.Context, in *ExportUserDataRequest, opts ...grpc.CallOption) (*ExportUserDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportUserDataResponse)
	err := c.cc.Invoke(ctx, EntDBService_ExportUserData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) FreezeUser(ctx context.Context, in *FreezeUserRequest, opts ...grpc.CallOption) (*FreezeUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FreezeUserResponse)
	err := c.cc.Invoke(ctx, EntDBService_FreezeUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) CancelUserDeletion(ctx context.Context, in *CancelUserDeletionRequest, opts ...grpc.CallOption) (*CancelUserDeletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelUserDeletionResponse)
	err := c.cc.Invoke(ctx, EntDBService_CancelUserDeletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) GetTenantQuota(ctx context.Context, in *GetTenantQuotaRequest, opts ...grpc.CallOption) (*GetTenantQuotaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTenantQuotaResponse)
	err := c.cc.Invoke(ctx, EntDBService_GetTenantQuota_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) GetNodeByKey(ctx context.Context, in *GetNodeByKeyRequest, opts ...grpc.CallOption) (*GetNodeByKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeByKeyResponse)
	err := c.cc.Invoke(ctx, EntDBService_GetNodeByKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entDBServiceClient) SearchNodes(ctx context.Context, in *SearchNodesRequest, opts ...grpc.CallOption) (*SearchNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchNodesResponse)
	err := c.cc.Invoke(ctx, EntDBService_SearchNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EntDBServiceServer is the server API for EntDBService service.
// All implementations must embed UnimplementedEntDBServiceServer
// for forward compatibility.
//
// EntDB Service - Main API for database operations
type EntDBServiceServer interface {
	// Execute an atomic transaction containing one or more operations
	// Returns a receipt that can be used to check application status
	ExecuteAtomic(context.Context, *ExecuteAtomicRequest) (*ExecuteAtomicResponse, error)
	// Get the status of a previously submitted transaction
	GetReceiptStatus(context.Context, *GetReceiptStatusRequest) (*GetReceiptStatusResponse, error)
	// Get a node by ID
	GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
	// Get multiple nodes by IDs
	GetNodes(context.Context, *GetNodesRequest) (*GetNodesResponse, error)
	// Query nodes by type with optional filters
	QueryNodes(context.Context, *QueryNodesRequest) (*QueryNodesResponse, error)
	// Get outgoing edges from a node
	GetEdgesFrom(context.Context, *GetEdgesRequest) (*GetEdgesResponse, error)
	// Get incoming edges to a node
	GetEdgesTo(context.Context, *GetEdgesRequest) (*GetEdgesResponse, error)
	// Search mailbox with full-text search
	SearchMailbox(context.Context, *SearchMailboxRequest) (*SearchMailboxResponse, error)
	// Get mailbox items for a user
	GetMailbox(context.Context, *GetMailboxRequest) (*GetMailboxResponse, error)
	// Get server health and status
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Get schema information
	GetSchema(context.Context, *GetSchemaRequest) (*GetSchemaResponse, error)
	// List all tenants that have data
	ListTenants(context.Context, *ListTenantsRequest) (*ListTenantsResponse, error)
	// List mailbox users for a tenant
	ListMailboxUsers(context.Context, *ListMailboxUsersRequest) (*ListMailboxUsersResponse, error)
	// Wait for a specific stream position to be applied
	WaitForOffset(context.Context, *WaitForOffsetRequest) (*WaitForOffsetResponse, error)
	// ACL v2 - Get connected nodes with ACL filtering
	GetConnectedNodes(context.Context, *GetConnectedNodesRequest) (*GetConnectedNodesResponse, error)
	// ACL v2 - Share a node with an actor
	ShareNode(context.Context, *ShareNodeRequest) (*ShareNodeResponse, error)
	// ACL v2 - Revoke access from an actor
	RevokeAccess(context.Context, *RevokeAccessRequest) (*RevokeAccessResponse, error)
	// ACL v2 - List nodes shared with the caller
	ListSharedWithMe(context.Context, *ListSharedWithMeRequest) (*ListSharedWithMeResponse, error)
	// ACL v2 - Add a member to a group
	AddGroupMember(context.Context, *GroupMemberRequest) (*GroupMemberResponse, error)
	// ACL v2 - Remove a member from a group
	RemoveGroupMember(context.Context, *GroupMemberRequest) (*GroupMemberResponse, error)
	// ACL v2 - Transfer ownership of a node
	TransferOwnership(context.Context, *TransferOwnershipRequest) (*TransferOwnershipResponse, error)
	// User registry CRUD
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	// Tenant registry CRUD
	CreateTenant(context.Context, *CreateTenantRequest) (*CreateTenantResponse, error)
	GetTenant(context.Context, *GetTenantRequest) (*GetTenantResponse, error)
	ArchiveTenant(context.Context, *ArchiveTenantRequest) (*ArchiveTenantResponse, error)
	// Tenant membership management
	AddTenantMember(context.Context, *TenantMemberRequest) (*TenantMemberResponse, error)
	RemoveTenantMember(context.Context, *TenantMemberRequest) (*TenantMemberResponse, error)
	GetTenantMembers(context.Context, *GetTenantMembersRequest) (*GetTenantMembersResponse, error)
	GetUserTenants(context.Context, *GetUserTenantsRequest) (*GetUserTenantsResponse, error)
	ChangeMemberRole(context.Context, *ChangeMemberRoleRequest) (*ChangeMemberRoleResponse, error)
	// Admin operations (Issue #90, ADR-003)
	TransferUserContent(context.Context, *TransferUserContentRequest) (*TransferUserContentResponse, error)
	DelegateAccess(context.Context, *DelegateAccessRequest) (*DelegateAccessResponse, error)
	SetLegalHold(context.Context, *LegalHoldRequest) (*LegalHoldResponse, error)
	RevokeAllUserAccess(context.Context, *RevokeAllUserAccessRequest) (*RevokeAllUserAccessResponse, error)
	// GDPR operations (Issue #103, ADR-004)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	ExportUserData(context.Context, *ExportUserDataRequest) (*ExportUserDataResponse, error)
	FreezeUser(context.Context, *FreezeUserRequest) (*FreezeUserResponse, error)
	CancelUserDeletion(context.Context, *CancelUserDeletionRequest) (*CancelUserDeletionResponse, error)
	// Quota dashboard (ADR: docs/decisions/quotas.md)
	GetTenantQuota(context.Context, *GetTenantQuotaRequest) (*GetTenantQuotaResponse, error)
	// Unique-key secondary lookup (2026-04-13 unique_keys decision)
	GetNodeByKey(context.Context, *GetNodeByKeyRequest) (*GetNodeByKeyResponse, error)
	// Full-text search across searchable fields (2026-04-19 FTS decision)
	SearchNodes(context.Context, *SearchNodesRequest) (*SearchNodesResponse, error)
	mustEmbedUnimplementedEntDBServiceServer()
}

// UnimplementedEntDBServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEntDBServiceServer struct{}

func (UnimplementedEntDBServiceServer) ExecuteAtomic(context.Context, *ExecuteAtomicRequest) (*ExecuteAtomicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteAtomic not implemented")
}
func (UnimplementedEntDBServiceServer) GetReceiptStatus(context.Context, *GetReceiptStatusRequest) (*GetReceiptStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReceiptStatus not implemented")
}
func (UnimplementedEntDBServiceServer) GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedEntDBServiceServer) GetNodes(context.Context, *GetNodesRequest) (*GetNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodes not implemented")
}
func (UnimplementedEntDBServiceServer) QueryNodes(context.Context, *QueryNodesRequest) (*QueryNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryNodes not implemented")
}
func (UnimplementedEntDBServiceServer) GetEdgesFrom(context.Context, *GetEdgesRequest) (*GetEdgesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEdgesFrom not implemented")
}
func (UnimplementedEntDBServiceServer) GetEdgesTo(context.Context, *GetEdgesRequest) (*GetEdgesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEdgesTo not implemented")
}
func (UnimplementedEntDBServiceServer) SearchMailbox(context.Context, *SearchMailboxRequest) (*SearchMailboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchMailbox not implemented")
}
func (UnimplementedEntDBServiceServer) GetMailbox(context.Context, *GetMailboxRequest) (*GetMailboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMailbox not implemented")
}
func (UnimplementedEntDBServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedEntDBServiceServer) GetSchema(context.Context, *GetSchemaRequest) (*GetSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSchema not implemented")
}
func (UnimplementedEntDBServiceServer) ListTenants(context.Context, *ListTenantsRequest) (*ListTenantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTenants not implemented")
}
func (UnimplementedEntDBServiceServer) ListMailboxUsers(context.Context, *ListMailboxUsersRequest) (*ListMailboxUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMailboxUsers not implemented")
}
func (UnimplementedEntDBServiceServer) WaitForOffset(context.Context, *WaitForOffsetRequest) (*WaitForOffsetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WaitForOffset not implemented")
}
func (UnimplementedEntDBServiceServer) GetConnectedNodes(context.Context, *GetConnectedNodesRequest) (*GetConnectedNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConnectedNodes not implemented")
}
func (UnimplementedEntDBServiceServer) ShareNode(context.Context, *ShareNodeRequest) (*ShareNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShareNode not implemented")
}
func (UnimplementedEntDBServiceServer) RevokeAccess(context.Context, *RevokeAccessRequest) (*RevokeAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeAccess not implemented")
}
func (UnimplementedEntDBServiceServer) ListSharedWithMe(context.Context, *ListSharedWithMeRequest) (*ListSharedWithMeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSharedWithMe not implemented")
}
func (UnimplementedEntDBServiceServer) AddGroupMember(context.Context, *GroupMemberRequest) (*GroupMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddGroupMember not implemented")
}
func (UnimplementedEntDBServiceServer) RemoveGroupMember(context.Context, *GroupMemberRequest) (*GroupMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveGroupMember not implemented")
}
func (UnimplementedEntDBServiceServer) TransferOwnership(context.Context, *TransferOwnershipRequest) (*TransferOwnershipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferOwnership not implemented")
}
func (UnimplementedEntDBServiceServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedEntDBServiceServer) GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedEntDBServiceServer) UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedEntDBServiceServer) ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedEntDBServiceServer) CreateTenant(context.Context, *CreateTenantRequest) (*CreateTenantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTenant not implemented")
}
func (UnimplementedEntDBServiceServer) GetTenant(context.Context, *GetTenantRequest) (*GetTenantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTenant not implemented")
}
func (UnimplementedEntDBServiceServer) ArchiveTenant(context.Context, *ArchiveTenantRequest) (*ArchiveTenantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ArchiveTenant not implemented")
}
func (UnimplementedEntDBServiceServer) AddTenantMember(context.Context, *TenantMemberRequest) (*TenantMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTenantMember not implemented")
}
func (UnimplementedEntDBServiceServer) RemoveTenantMember(context.Context, *TenantMemberRequest) (*TenantMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveTenantMember not implemented")
}
func (UnimplementedEntDBServiceServer) GetTenantMembers(context.Context, *GetTenantMembersRequest) (*GetTenantMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTenantMembers not implemented")
}
func (UnimplementedEntDBServiceServer) GetUserTenants(context.Context, *GetUserTenantsRequest) (*GetUserTenantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserTenants not implemented")
}
func (UnimplementedEntDBServiceServer) ChangeMemberRole(context.Context, *ChangeMemberRoleRequest) (*ChangeMemberRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeMemberRole not implemented")
}
func (UnimplementedEntDBServiceServer) TransferUserContent(context.Context, *TransferUserContentRequest) (*TransferUserContentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferUserContent not implemented")
}
func (UnimplementedEntDBServiceServer) DelegateAccess(context.Context, *DelegateAccessRequest) (*DelegateAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DelegateAccess not implemented")
}
func (UnimplementedEntDBServiceServer) SetLegalHold(context.Context, *LegalHoldRequest) (*LegalHoldResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetLegalHold not implemented")
}
func (UnimplementedEntDBServiceServer) RevokeAllUserAccess(context.Context, *RevokeAllUserAccessRequest) (*RevokeAllUserAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeAllUserAccess not implemented")
}
func (UnimplementedEntDBServiceServer) DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedEntDBServiceServer) ExportUserData(context.Context, *ExportUserDataRequest) (*ExportUserDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportUserData not implemented")
}
func (UnimplementedEntDBServiceServer) FreezeUser(context.Context, *FreezeUserRequest) (*FreezeUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FreezeUser not implemented")
}
func (UnimplementedEntDBServiceServer) CancelUserDeletion(context.Context, *CancelUserDeletionRequest) (*CancelUserDeletionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelUserDeletion not implemented")
}
func (UnimplementedEntDBServiceServer) GetTenantQuota(context.Context, *GetTenantQuotaRequest) (*GetTenantQuotaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTenantQuota not implemented")
}
func (UnimplementedEntDBServiceServer) GetNodeByKey(context.Context, *GetNodeByKeyRequest) (*GetNodeByKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeByKey not implemented")
}
func (UnimplementedEntDBServiceServer) SearchNodes(context.Context, *SearchNodesRequest) (*SearchNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchNodes not implemented")
}
func (UnimplementedEntDBServiceServer) mustEmbedUnimplementedEntDBServiceServer() {}
func (UnimplementedEntDBServiceServer) testEmbeddedByValue()                      {}

// UnsafeEntDBServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EntDBServiceServer will
// result in compilation errors.
type UnsafeEntDBServiceServer interface {
	mustEmbedUnimplementedEntDBServiceServer()
}

func RegisterEntDBServiceServer(s grpc.ServiceRegistrar, srv EntDBServiceServer) {
	// If the following call panics, it indicates UnimplementedEntDBServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EntDBService_ServiceDesc, srv)
}

func _EntDBService_ExecuteAtomic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteAtomicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).ExecuteAtomic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_ExecuteAtomic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).ExecuteAtomic(ctx, req.(*ExecuteAtomicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_GetReceiptStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReceiptStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).GetReceiptStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_GetReceiptStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).GetReceiptStatus(ctx, req.(*GetReceiptStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_GetNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).GetNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_GetNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).GetNodes(ctx, req.(*GetNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_QueryNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).QueryNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_QueryNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).QueryNodes(ctx, req.(*QueryNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_GetEdgesFrom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEdgesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).GetEdgesFrom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_GetEdgesFrom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).GetEdgesFrom(ctx, req.(*GetEdgesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_GetEdgesTo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEdgesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).GetEdgesTo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_GetEdgesTo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).GetEdgesTo(ctx, req.(*GetEdgesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_SearchMailbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchMailboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).SearchMailbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_SearchMailbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).SearchMailbox(ctx, req.(*SearchMailboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_GetMailbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMailboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).GetMailbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_GetMailbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).GetMailbox(ctx, req.(*GetMailboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_GetSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).GetSchema(ctx, req.(*GetSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_ListTenants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTenantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).ListTenants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_ListTenants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).ListTenants(ctx, req.(*ListTenantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_ListMailboxUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMailboxUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).ListMailboxUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_ListMailboxUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).ListMailboxUsers(ctx, req.(*ListMailboxUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_WaitForOffset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitForOffsetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).WaitForOffset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_WaitForOffset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).WaitForOffset(ctx, req.(*WaitForOffsetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_GetConnectedNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnectedNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).GetConnectedNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_GetConnectedNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).GetConnectedNodes(ctx, req.(*GetConnectedNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_ShareNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).ShareNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_ShareNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).ShareNode(ctx, req.(*ShareNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_RevokeAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).RevokeAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_RevokeAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).RevokeAccess(ctx, req.(*RevokeAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_ListSharedWithMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSharedWithMeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).ListSharedWithMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_ListSharedWithMe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).ListSharedWithMe(ctx, req.(*ListSharedWithMeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_AddGroupMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).AddGroupMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_AddGroupMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).AddGroupMember(ctx, req.(*GroupMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_RemoveGroupMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).RemoveGroupMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_RemoveGroupMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).RemoveGroupMember(ctx, req.(*GroupMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_TransferOwnership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferOwnershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).TransferOwnership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_TransferOwnership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).TransferOwnership(ctx, req.(*TransferOwnershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_ListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_CreateTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).CreateTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_CreateTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).CreateTenant(ctx, req.(*CreateTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_GetTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).GetTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_GetTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).GetTenant(ctx, req.(*GetTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_ArchiveTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).ArchiveTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_ArchiveTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).ArchiveTenant(ctx, req.(*ArchiveTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_AddTenantMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).AddTenantMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_AddTenantMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).AddTenantMember(ctx, req.(*TenantMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_RemoveTenantMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).RemoveTenantMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_RemoveTenantMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).RemoveTenantMember(ctx, req.(*TenantMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_GetTenantMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).GetTenantMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_GetTenantMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).GetTenantMembers(ctx, req.(*GetTenantMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_GetUserTenants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTenantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).GetUserTenants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_GetUserTenants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).GetUserTenants(ctx, req.(*GetUserTenantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_ChangeMemberRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeMemberRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).ChangeMemberRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_ChangeMemberRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).ChangeMemberRole(ctx, req.(*ChangeMemberRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_TransferUserContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferUserContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).TransferUserContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_TransferUserContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).TransferUserContent(ctx, req.(*TransferUserContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_DelegateAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelegateAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).DelegateAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_DelegateAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).DelegateAccess(ctx, req.(*DelegateAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_SetLegalHold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LegalHoldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).SetLegalHold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_SetLegalHold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).SetLegalHold(ctx, req.(*LegalHoldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_RevokeAllUserAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeAllUserAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).RevokeAllUserAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_RevokeAllUserAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).RevokeAllUserAccess(ctx, req.(*RevokeAllUserAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_ExportUserData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportUserDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).ExportUserData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_ExportUserData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).ExportUserData(ctx, req.(*ExportUserDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_FreezeUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FreezeUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).FreezeUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_FreezeUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).FreezeUser(ctx, req.(*FreezeUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_CancelUserDeletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelUserDeletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).CancelUserDeletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_CancelUserDeletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).CancelUserDeletion(ctx, req.(*CancelUserDeletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_GetTenantQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).GetTenantQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_GetTenantQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).GetTenantQuota(ctx, req.(*GetTenantQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_GetNodeByKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeByKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).GetNodeByKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_GetNodeByKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).GetNodeByKey(ctx, req.(*GetNodeByKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntDBService_SearchNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntDBServiceServer).SearchNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntDBService_SearchNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntDBServiceServer).SearchNodes(ctx, req.(*SearchNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EntDBService_ServiceDesc is the grpc.ServiceDesc for EntDBService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EntDBService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "entdb.v1.EntDBService",
	HandlerType: (*EntDBServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteAtomic",
			Handler:    _EntDBService_ExecuteAtomic_Handler,
		},
		{
			MethodName: "GetReceiptStatus",
			Handler:    _EntDBService_GetReceiptStatus_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _EntDBService_GetNode_Handler,
		},
		{
			MethodName: "GetNodes",
			Handler:    _EntDBService_GetNodes_Handler,
		},
		{
			MethodName: "QueryNodes",
			Handler:    _EntDBService_QueryNodes_Handler,
		},
		{
			MethodName: "GetEdgesFrom",
			Handler:    _EntDBService_GetEdgesFrom_Handler,
		},
		{
			MethodName: "GetEdgesTo",
			Handler:    _EntDBService_GetEdgesTo_Handler,
		},
		{
			MethodName: "SearchMailbox",
			Handler:    _EntDBService_SearchMailbox_Handler,
		},
		{
			MethodName: "GetMailbox",
			Handler:    _EntDBService_GetMailbox_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _EntDBService_Health_Handler,
		},
		{
			MethodName: "GetSchema",
			Handler:    _EntDBService_GetSchema_Handler,
		},
		{
			MethodName: "ListTenants",
			Handler:    _EntDBService_ListTenants_Handler,
		},
		{
			MethodName: "ListMailboxUsers",
			Handler:    _EntDBService_ListMailboxUsers_Handler,
		},
		{
			MethodName: "WaitForOffset",
			Handler:    _EntDBService_WaitForOffset_Handler,
		},
		{
			MethodName: "GetConnectedNodes",
			Handler:    _EntDBService_GetConnectedNodes_Handler,
		},
		{
			MethodName: "ShareNode",
			Handler:    _EntDBService_ShareNode_Handler,
		},
		{
			MethodName: "RevokeAccess",
			Handler:    _EntDBService_RevokeAccess_Handler,
		},
		{
			MethodName: "ListSharedWithMe",
			Handler:    _EntDBService_ListSharedWithMe_Handler,
		},
		{
			MethodName: "AddGroupMember",
			Handler:    _EntDBService_AddGroupMember_Handler,
		},
		{
			MethodName: "RemoveGroupMember",
			Handler:    _EntDBService_RemoveGroupMember_Handler,
		},
		{
			MethodName: "TransferOwnership",
			Handler:    _EntDBService_TransferOwnership_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _EntDBService_CreateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _EntDBService_GetUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _EntDBService_UpdateUser_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _EntDBService_ListUsers_Handler,
		},
		{
			MethodName: "CreateTenant",
			Handler:    _EntDBService_CreateTenant_Handler,
		},
		{
			MethodName: "GetTenant",
			Handler:    _EntDBService_GetTenant_Handler,
		},
		{
			MethodName: "ArchiveTenant",
			Handler:    _EntDBService_ArchiveTenant_Handler,
		},
		{
			MethodName: "AddTenantMember",
			Handler:    _EntDBService_AddTenantMember_Handler,
		},
		{
			MethodName: "RemoveTenantMember",
			Handler:    _EntDBService_RemoveTenantMember_Handler,
		},
		{
			MethodName: "GetTenantMembers",
			Handler:    _EntDBService_GetTenantMembers_Handler,
		},
		{
			MethodName: "GetUserTenants",
			Handler:    _EntDBService_GetUserTenants_Handler,
		},
		{
			MethodName: "ChangeMemberRole",
			Handler:    _EntDBService_ChangeMemberRole_Handler,
		},
		{
			MethodName: "TransferUserContent",
			Handler:    _EntDBService_TransferUserContent_Handler,
		},
		{
			MethodName: "DelegateAccess",
			Handler:    _EntDBService_DelegateAccess_Handler,
		},
		{
			MethodName: "SetLegalHold",
			Handler:    _EntDBService_SetLegalHold_Handler,
		},
		{
			MethodName: "RevokeAllUserAccess",
			Handler:    _EntDBService_RevokeAllUserAccess_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _EntDBService_DeleteUser_Handler,
		},
		{
			MethodName: "ExportUserData",
			Handler:    _EntDBService_ExportUserData_Handler,
		},
		{
			MethodName: "FreezeUser",
			Handler:    _EntDBService_FreezeUser_Handler,
		},
		{
			MethodName: "CancelUserDeletion",
			Handler:    _EntDBService_CancelUserDeletion_Handler,
		},
		{
			MethodName: "GetTenantQuota",
			Handler:    _EntDBService_GetTenantQuota_Handler,
		},
		{
			MethodName: "GetNodeByKey",
			Handler:    _EntDBService_GetNodeByKey_Handler,
		},
		{
			MethodName: "SearchNodes",
			Handler:    _EntDBService_SearchNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "entdb.proto",
}
