# ruff: noqa
# fmt: off
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: test_schema.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'test_schema.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sdk.entdb_sdk._generated import entdb_options_pb2 as entdb__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11test_schema.proto\x12\nentdb.test\x1a\x13\x65ntdb_options.proto\"\xb6\x01\n\x07Product\x12\x13\n\x03sku\x18\x01 \x01(\tB\x06\xb2\xbb\x18\x02h\x01\x12\x14\n\x04name\x18\x02 \x01(\tB\x06\xb2\xbb\x18\x02\x10\x01\x12\x1e\n\x0bprice_cents\x18\x03 \x01(\x03\x42\t\xb2\xbb\x18\x05:\x03int\x12\x32\n\x06status\x18\x04 \x01(\tB\"\xb2\xbb\x18\x1e\x32\x15\x64raft,active,archivedJ\x05\x64raft:,\xa2\xbb\x18(\x08\xa9\x46R#Test product type with a unique sku\"K\n\x08\x43\x61tegory\x12\x14\n\x04slug\x18\x01 \x01(\tB\x06\xb2\xbb\x18\x02h\x01\x12\x0c\n\x04name\x18\x02 \x01(\t:\x1b\xa2\xbb\x18\x17\x08\xaa\x46R\x12Test category type\"X\n\tBelongsTo\x12\x19\n\x06weight\x18\x01 \x01(\x03\x42\t\xb2\xbb\x18\x05:\x03int:0\xaa\xbb\x18,\x08\x8dG\x12\nbelongs_toJ\x1bProduct belongs to categoryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_schema_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCT'].fields_by_name['sku']._loaded_options = None
  _globals['_PRODUCT'].fields_by_name['sku']._serialized_options = b'\262\273\030\002h\001'
  _globals['_PRODUCT'].fields_by_name['name']._loaded_options = None
  _globals['_PRODUCT'].fields_by_name['name']._serialized_options = b'\262\273\030\002\020\001'
  _globals['_PRODUCT'].fields_by_name['price_cents']._loaded_options = None
  _globals['_PRODUCT'].fields_by_name['price_cents']._serialized_options = b'\262\273\030\005:\003int'
  _globals['_PRODUCT'].fields_by_name['status']._loaded_options = None
  _globals['_PRODUCT'].fields_by_name['status']._serialized_options = b'\262\273\030\0362\025draft,active,archivedJ\005draft'
  _globals['_PRODUCT']._loaded_options = None
  _globals['_PRODUCT']._serialized_options = b'\242\273\030(\010\251FR#Test product type with a unique sku'
  _globals['_CATEGORY'].fields_by_name['slug']._loaded_options = None
  _globals['_CATEGORY'].fields_by_name['slug']._serialized_options = b'\262\273\030\002h\001'
  _globals['_CATEGORY']._loaded_options = None
  _globals['_CATEGORY']._serialized_options = b'\242\273\030\027\010\252FR\022Test category type'
  _globals['_BELONGSTO'].fields_by_name['weight']._loaded_options = None
  _globals['_BELONGSTO'].fields_by_name['weight']._serialized_options = b'\262\273\030\005:\003int'
  _globals['_BELONGSTO']._loaded_options = None
  _globals['_BELONGSTO']._serialized_options = b'\252\273\030,\010\215G\022\nbelongs_toJ\033Product belongs to category'
  _globals['_PRODUCT']._serialized_start=55
  _globals['_PRODUCT']._serialized_end=237
  _globals['_CATEGORY']._serialized_start=239
  _globals['_CATEGORY']._serialized_end=314
  _globals['_BELONGSTO']._serialized_start=316
  _globals['_BELONGSTO']._serialized_end=404
# @@protoc_insertion_point(module_scope)
