# ruff: noqa
# fmt: off
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: example_schema.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'example_schema.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from entdb_sdk._generated import entdb_options_pb2 as entdb__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x65xample_schema.proto\x12\x0e\x65ntdb.examples\x1a\x13\x65ntdb_options.proto\"f\n\x04User\x12\x15\n\x05\x65mail\x18\x01 \x01(\tB\x06\xb2\xbb\x18\x02h\x01\x12\x14\n\x04name\x18\x02 \x01(\tB\x06\xb2\xbb\x18\x02\x10\x01:1\xa2\xbb\x18-\x08\x01R)Example user (matches contract-seed User)\"e\n\x04Task\x12\x15\n\x05title\x18\x01 \x01(\tB\x06\xb2\xbb\x18\x02\x10\x01\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t:1\xa2\xbb\x18-\x08\x02R)Example task (matches contract-seed Task)\"9\n\nAssignedTo:+\xaa\xbb\x18\'\x08\x64\x12\nAssignedToJ\x17Task assigned to a Userb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_schema_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER'].fields_by_name['email']._loaded_options = None
  _globals['_USER'].fields_by_name['email']._serialized_options = b'\262\273\030\002h\001'
  _globals['_USER'].fields_by_name['name']._loaded_options = None
  _globals['_USER'].fields_by_name['name']._serialized_options = b'\262\273\030\002\020\001'
  _globals['_USER']._loaded_options = None
  _globals['_USER']._serialized_options = b'\242\273\030-\010\001R)Example user (matches contract-seed User)'
  _globals['_TASK'].fields_by_name['title']._loaded_options = None
  _globals['_TASK'].fields_by_name['title']._serialized_options = b'\262\273\030\002\020\001'
  _globals['_TASK']._loaded_options = None
  _globals['_TASK']._serialized_options = b'\242\273\030-\010\002R)Example task (matches contract-seed Task)'
  _globals['_ASSIGNEDTO']._loaded_options = None
  _globals['_ASSIGNEDTO']._serialized_options = b'\252\273\030\'\010d\022\nAssignedToJ\027Task assigned to a User'
  _globals['_USER']._serialized_start=61
  _globals['_USER']._serialized_end=163
  _globals['_TASK']._serialized_start=165
  _globals['_TASK']._serialized_end=266
  _globals['_ASSIGNEDTO']._serialized_start=268
  _globals['_ASSIGNEDTO']._serialized_end=325
# @@protoc_insertion_point(module_scope)
