// EntDB Console — curated, browser-facing API.
//
// This proto file is the LITERAL access policy for the entdb-console binary.
// Every RPC the browser is allowed to call MUST be declared here. Anything
// not listed is unreachable from the SPA — the ConnectRPC handler has no
// route for it, full stop. This is intentional: the proto is the security
// boundary, not a stylistic choice.
//
// Each RPC reuses the request/response messages from the upstream
// `entdb.v1.EntDBService` proto so each Console handler is a one-line
// pass-through to the upstream gRPC client. Adding a new RPC therefore
// requires touching this file (and getting it through review) rather
// than just exposing whatever the upstream happens to support.
//
// Scope (PR 2): read-only RPCs from PR 1, plus narrow sandbox-only
// CREATE write RPCs (`SandboxCreateNode`, `SandboxCreateEdge`). Writes
// are gated to a single configured sandbox tenant; the console binary
// rejects any other tenant id at the handler. The sandbox RPCs use
// narrow request/response messages defined in this file (NOT
// `entdb.v1.ExecuteAtomicRequest`) so the browser can never construct
// a multi-op transaction or target arbitrary fields outside the
// curated CREATE shape. The handler builds the underlying single-op
// `ExecuteAtomicRequest` itself before forwarding upstream.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: console.proto

package consolev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/elloloop/tenant-shard-db/sdk/go/entdb/internal/console/v1"
	pb "github.com/elloloop/tenant-shard-db/sdk/go/entdb/internal/pb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ConsoleName is the fully-qualified name of the Console service.
	ConsoleName = "entdb.console.v1.Console"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ConsoleHealthProcedure is the fully-qualified name of the Console's Health RPC.
	ConsoleHealthProcedure = "/entdb.console.v1.Console/Health"
	// ConsoleListTenantsProcedure is the fully-qualified name of the Console's ListTenants RPC.
	ConsoleListTenantsProcedure = "/entdb.console.v1.Console/ListTenants"
	// ConsoleGetTenantProcedure is the fully-qualified name of the Console's GetTenant RPC.
	ConsoleGetTenantProcedure = "/entdb.console.v1.Console/GetTenant"
	// ConsoleGetSchemaProcedure is the fully-qualified name of the Console's GetSchema RPC.
	ConsoleGetSchemaProcedure = "/entdb.console.v1.Console/GetSchema"
	// ConsoleQueryNodesProcedure is the fully-qualified name of the Console's QueryNodes RPC.
	ConsoleQueryNodesProcedure = "/entdb.console.v1.Console/QueryNodes"
	// ConsoleGetNodeProcedure is the fully-qualified name of the Console's GetNode RPC.
	ConsoleGetNodeProcedure = "/entdb.console.v1.Console/GetNode"
	// ConsoleGetEdgesFromProcedure is the fully-qualified name of the Console's GetEdgesFrom RPC.
	ConsoleGetEdgesFromProcedure = "/entdb.console.v1.Console/GetEdgesFrom"
	// ConsoleGetEdgesToProcedure is the fully-qualified name of the Console's GetEdgesTo RPC.
	ConsoleGetEdgesToProcedure = "/entdb.console.v1.Console/GetEdgesTo"
	// ConsoleGetConnectedNodesProcedure is the fully-qualified name of the Console's GetConnectedNodes
	// RPC.
	ConsoleGetConnectedNodesProcedure = "/entdb.console.v1.Console/GetConnectedNodes"
	// ConsoleSearchMailboxProcedure is the fully-qualified name of the Console's SearchMailbox RPC.
	ConsoleSearchMailboxProcedure = "/entdb.console.v1.Console/SearchMailbox"
	// ConsoleSandboxCreateNodeProcedure is the fully-qualified name of the Console's SandboxCreateNode
	// RPC.
	ConsoleSandboxCreateNodeProcedure = "/entdb.console.v1.Console/SandboxCreateNode"
	// ConsoleSandboxCreateEdgeProcedure is the fully-qualified name of the Console's SandboxCreateEdge
	// RPC.
	ConsoleSandboxCreateEdgeProcedure = "/entdb.console.v1.Console/SandboxCreateEdge"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	consoleServiceDescriptor                 = v1.File_console_proto.Services().ByName("Console")
	consoleHealthMethodDescriptor            = consoleServiceDescriptor.Methods().ByName("Health")
	consoleListTenantsMethodDescriptor       = consoleServiceDescriptor.Methods().ByName("ListTenants")
	consoleGetTenantMethodDescriptor         = consoleServiceDescriptor.Methods().ByName("GetTenant")
	consoleGetSchemaMethodDescriptor         = consoleServiceDescriptor.Methods().ByName("GetSchema")
	consoleQueryNodesMethodDescriptor        = consoleServiceDescriptor.Methods().ByName("QueryNodes")
	consoleGetNodeMethodDescriptor           = consoleServiceDescriptor.Methods().ByName("GetNode")
	consoleGetEdgesFromMethodDescriptor      = consoleServiceDescriptor.Methods().ByName("GetEdgesFrom")
	consoleGetEdgesToMethodDescriptor        = consoleServiceDescriptor.Methods().ByName("GetEdgesTo")
	consoleGetConnectedNodesMethodDescriptor = consoleServiceDescriptor.Methods().ByName("GetConnectedNodes")
	consoleSearchMailboxMethodDescriptor     = consoleServiceDescriptor.Methods().ByName("SearchMailbox")
	consoleSandboxCreateNodeMethodDescriptor = consoleServiceDescriptor.Methods().ByName("SandboxCreateNode")
	consoleSandboxCreateEdgeMethodDescriptor = consoleServiceDescriptor.Methods().ByName("SandboxCreateEdge")
)

// ConsoleClient is a client for the entdb.console.v1.Console service.
type ConsoleClient interface {
	// Liveness/readiness probe for the console binary itself. Forwards to
	// upstream Health so the response also reflects upstream availability.
	Health(context.Context, *connect.Request[pb.HealthRequest]) (*connect.Response[pb.HealthResponse], error)
	// List tenants the configured caller can see.
	ListTenants(context.Context, *connect.Request[pb.ListTenantsRequest]) (*connect.Response[pb.ListTenantsResponse], error)
	// Get a tenant by id.
	GetTenant(context.Context, *connect.Request[pb.GetTenantRequest]) (*connect.Response[pb.GetTenantResponse], error)
	// Get the active schema (optionally for a specific type).
	GetSchema(context.Context, *connect.Request[pb.GetSchemaRequest]) (*connect.Response[pb.GetSchemaResponse], error)
	// Query nodes by type with typed filters + pagination.
	QueryNodes(context.Context, *connect.Request[pb.QueryNodesRequest]) (*connect.Response[pb.QueryNodesResponse], error)
	// Get a single node by id.
	GetNode(context.Context, *connect.Request[pb.GetNodeRequest]) (*connect.Response[pb.GetNodeResponse], error)
	// Outgoing edges from a node.
	GetEdgesFrom(context.Context, *connect.Request[pb.GetEdgesRequest]) (*connect.Response[pb.GetEdgesResponse], error)
	// Incoming edges to a node.
	GetEdgesTo(context.Context, *connect.Request[pb.GetEdgesRequest]) (*connect.Response[pb.GetEdgesResponse], error)
	// Connected nodes (ACL-filtered) for a graph view.
	GetConnectedNodes(context.Context, *connect.Request[pb.GetConnectedNodesRequest]) (*connect.Response[pb.GetConnectedNodesResponse], error)
	// Search a user mailbox.
	SearchMailbox(context.Context, *connect.Request[pb.SearchMailboxRequest]) (*connect.Response[pb.SearchMailboxResponse], error)
	// Create a single node in the configured sandbox tenant.
	//
	// The handler:
	//  1. Rejects with `unimplemented` if no sandbox tenant is configured.
	//  2. Rejects with `permission_denied` if `tenant_id` does not match
	//     the configured sandbox tenant.
	//  3. Builds a single-op `entdb.v1.ExecuteAtomicRequest` with
	//     `wait_applied = true` so success means the write is applied,
	//     not just queued.
	SandboxCreateNode(context.Context, *connect.Request[v1.SandboxCreateNodeRequest]) (*connect.Response[v1.SandboxCreateNodeResponse], error)
	// Create a single edge in the configured sandbox tenant. Same gating
	// semantics as `SandboxCreateNode`.
	SandboxCreateEdge(context.Context, *connect.Request[v1.SandboxCreateEdgeRequest]) (*connect.Response[v1.SandboxCreateEdgeResponse], error)
}

// NewConsoleClient constructs a client for the entdb.console.v1.Console service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewConsoleClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ConsoleClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &consoleClient{
		health: connect.NewClient[pb.HealthRequest, pb.HealthResponse](
			httpClient,
			baseURL+ConsoleHealthProcedure,
			connect.WithSchema(consoleHealthMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		listTenants: connect.NewClient[pb.ListTenantsRequest, pb.ListTenantsResponse](
			httpClient,
			baseURL+ConsoleListTenantsProcedure,
			connect.WithSchema(consoleListTenantsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getTenant: connect.NewClient[pb.GetTenantRequest, pb.GetTenantResponse](
			httpClient,
			baseURL+ConsoleGetTenantProcedure,
			connect.WithSchema(consoleGetTenantMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getSchema: connect.NewClient[pb.GetSchemaRequest, pb.GetSchemaResponse](
			httpClient,
			baseURL+ConsoleGetSchemaProcedure,
			connect.WithSchema(consoleGetSchemaMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		queryNodes: connect.NewClient[pb.QueryNodesRequest, pb.QueryNodesResponse](
			httpClient,
			baseURL+ConsoleQueryNodesProcedure,
			connect.WithSchema(consoleQueryNodesMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getNode: connect.NewClient[pb.GetNodeRequest, pb.GetNodeResponse](
			httpClient,
			baseURL+ConsoleGetNodeProcedure,
			connect.WithSchema(consoleGetNodeMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getEdgesFrom: connect.NewClient[pb.GetEdgesRequest, pb.GetEdgesResponse](
			httpClient,
			baseURL+ConsoleGetEdgesFromProcedure,
			connect.WithSchema(consoleGetEdgesFromMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getEdgesTo: connect.NewClient[pb.GetEdgesRequest, pb.GetEdgesResponse](
			httpClient,
			baseURL+ConsoleGetEdgesToProcedure,
			connect.WithSchema(consoleGetEdgesToMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getConnectedNodes: connect.NewClient[pb.GetConnectedNodesRequest, pb.GetConnectedNodesResponse](
			httpClient,
			baseURL+ConsoleGetConnectedNodesProcedure,
			connect.WithSchema(consoleGetConnectedNodesMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		searchMailbox: connect.NewClient[pb.SearchMailboxRequest, pb.SearchMailboxResponse](
			httpClient,
			baseURL+ConsoleSearchMailboxProcedure,
			connect.WithSchema(consoleSearchMailboxMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		sandboxCreateNode: connect.NewClient[v1.SandboxCreateNodeRequest, v1.SandboxCreateNodeResponse](
			httpClient,
			baseURL+ConsoleSandboxCreateNodeProcedure,
			connect.WithSchema(consoleSandboxCreateNodeMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		sandboxCreateEdge: connect.NewClient[v1.SandboxCreateEdgeRequest, v1.SandboxCreateEdgeResponse](
			httpClient,
			baseURL+ConsoleSandboxCreateEdgeProcedure,
			connect.WithSchema(consoleSandboxCreateEdgeMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// consoleClient implements ConsoleClient.
type consoleClient struct {
	health            *connect.Client[pb.HealthRequest, pb.HealthResponse]
	listTenants       *connect.Client[pb.ListTenantsRequest, pb.ListTenantsResponse]
	getTenant         *connect.Client[pb.GetTenantRequest, pb.GetTenantResponse]
	getSchema         *connect.Client[pb.GetSchemaRequest, pb.GetSchemaResponse]
	queryNodes        *connect.Client[pb.QueryNodesRequest, pb.QueryNodesResponse]
	getNode           *connect.Client[pb.GetNodeRequest, pb.GetNodeResponse]
	getEdgesFrom      *connect.Client[pb.GetEdgesRequest, pb.GetEdgesResponse]
	getEdgesTo        *connect.Client[pb.GetEdgesRequest, pb.GetEdgesResponse]
	getConnectedNodes *connect.Client[pb.GetConnectedNodesRequest, pb.GetConnectedNodesResponse]
	searchMailbox     *connect.Client[pb.SearchMailboxRequest, pb.SearchMailboxResponse]
	sandboxCreateNode *connect.Client[v1.SandboxCreateNodeRequest, v1.SandboxCreateNodeResponse]
	sandboxCreateEdge *connect.Client[v1.SandboxCreateEdgeRequest, v1.SandboxCreateEdgeResponse]
}

// Health calls entdb.console.v1.Console.Health.
func (c *consoleClient) Health(ctx context.Context, req *connect.Request[pb.HealthRequest]) (*connect.Response[pb.HealthResponse], error) {
	return c.health.CallUnary(ctx, req)
}

// ListTenants calls entdb.console.v1.Console.ListTenants.
func (c *consoleClient) ListTenants(ctx context.Context, req *connect.Request[pb.ListTenantsRequest]) (*connect.Response[pb.ListTenantsResponse], error) {
	return c.listTenants.CallUnary(ctx, req)
}

// GetTenant calls entdb.console.v1.Console.GetTenant.
func (c *consoleClient) GetTenant(ctx context.Context, req *connect.Request[pb.GetTenantRequest]) (*connect.Response[pb.GetTenantResponse], error) {
	return c.getTenant.CallUnary(ctx, req)
}

// GetSchema calls entdb.console.v1.Console.GetSchema.
func (c *consoleClient) GetSchema(ctx context.Context, req *connect.Request[pb.GetSchemaRequest]) (*connect.Response[pb.GetSchemaResponse], error) {
	return c.getSchema.CallUnary(ctx, req)
}

// QueryNodes calls entdb.console.v1.Console.QueryNodes.
func (c *consoleClient) QueryNodes(ctx context.Context, req *connect.Request[pb.QueryNodesRequest]) (*connect.Response[pb.QueryNodesResponse], error) {
	return c.queryNodes.CallUnary(ctx, req)
}

// GetNode calls entdb.console.v1.Console.GetNode.
func (c *consoleClient) GetNode(ctx context.Context, req *connect.Request[pb.GetNodeRequest]) (*connect.Response[pb.GetNodeResponse], error) {
	return c.getNode.CallUnary(ctx, req)
}

// GetEdgesFrom calls entdb.console.v1.Console.GetEdgesFrom.
func (c *consoleClient) GetEdgesFrom(ctx context.Context, req *connect.Request[pb.GetEdgesRequest]) (*connect.Response[pb.GetEdgesResponse], error) {
	return c.getEdgesFrom.CallUnary(ctx, req)
}

// GetEdgesTo calls entdb.console.v1.Console.GetEdgesTo.
func (c *consoleClient) GetEdgesTo(ctx context.Context, req *connect.Request[pb.GetEdgesRequest]) (*connect.Response[pb.GetEdgesResponse], error) {
	return c.getEdgesTo.CallUnary(ctx, req)
}

// GetConnectedNodes calls entdb.console.v1.Console.GetConnectedNodes.
func (c *consoleClient) GetConnectedNodes(ctx context.Context, req *connect.Request[pb.GetConnectedNodesRequest]) (*connect.Response[pb.GetConnectedNodesResponse], error) {
	return c.getConnectedNodes.CallUnary(ctx, req)
}

// SearchMailbox calls entdb.console.v1.Console.SearchMailbox.
func (c *consoleClient) SearchMailbox(ctx context.Context, req *connect.Request[pb.SearchMailboxRequest]) (*connect.Response[pb.SearchMailboxResponse], error) {
	return c.searchMailbox.CallUnary(ctx, req)
}

// SandboxCreateNode calls entdb.console.v1.Console.SandboxCreateNode.
func (c *consoleClient) SandboxCreateNode(ctx context.Context, req *connect.Request[v1.SandboxCreateNodeRequest]) (*connect.Response[v1.SandboxCreateNodeResponse], error) {
	return c.sandboxCreateNode.CallUnary(ctx, req)
}

// SandboxCreateEdge calls entdb.console.v1.Console.SandboxCreateEdge.
func (c *consoleClient) SandboxCreateEdge(ctx context.Context, req *connect.Request[v1.SandboxCreateEdgeRequest]) (*connect.Response[v1.SandboxCreateEdgeResponse], error) {
	return c.sandboxCreateEdge.CallUnary(ctx, req)
}

// ConsoleHandler is an implementation of the entdb.console.v1.Console service.
type ConsoleHandler interface {
	// Liveness/readiness probe for the console binary itself. Forwards to
	// upstream Health so the response also reflects upstream availability.
	Health(context.Context, *connect.Request[pb.HealthRequest]) (*connect.Response[pb.HealthResponse], error)
	// List tenants the configured caller can see.
	ListTenants(context.Context, *connect.Request[pb.ListTenantsRequest]) (*connect.Response[pb.ListTenantsResponse], error)
	// Get a tenant by id.
	GetTenant(context.Context, *connect.Request[pb.GetTenantRequest]) (*connect.Response[pb.GetTenantResponse], error)
	// Get the active schema (optionally for a specific type).
	GetSchema(context.Context, *connect.Request[pb.GetSchemaRequest]) (*connect.Response[pb.GetSchemaResponse], error)
	// Query nodes by type with typed filters + pagination.
	QueryNodes(context.Context, *connect.Request[pb.QueryNodesRequest]) (*connect.Response[pb.QueryNodesResponse], error)
	// Get a single node by id.
	GetNode(context.Context, *connect.Request[pb.GetNodeRequest]) (*connect.Response[pb.GetNodeResponse], error)
	// Outgoing edges from a node.
	GetEdgesFrom(context.Context, *connect.Request[pb.GetEdgesRequest]) (*connect.Response[pb.GetEdgesResponse], error)
	// Incoming edges to a node.
	GetEdgesTo(context.Context, *connect.Request[pb.GetEdgesRequest]) (*connect.Response[pb.GetEdgesResponse], error)
	// Connected nodes (ACL-filtered) for a graph view.
	GetConnectedNodes(context.Context, *connect.Request[pb.GetConnectedNodesRequest]) (*connect.Response[pb.GetConnectedNodesResponse], error)
	// Search a user mailbox.
	SearchMailbox(context.Context, *connect.Request[pb.SearchMailboxRequest]) (*connect.Response[pb.SearchMailboxResponse], error)
	// Create a single node in the configured sandbox tenant.
	//
	// The handler:
	//  1. Rejects with `unimplemented` if no sandbox tenant is configured.
	//  2. Rejects with `permission_denied` if `tenant_id` does not match
	//     the configured sandbox tenant.
	//  3. Builds a single-op `entdb.v1.ExecuteAtomicRequest` with
	//     `wait_applied = true` so success means the write is applied,
	//     not just queued.
	SandboxCreateNode(context.Context, *connect.Request[v1.SandboxCreateNodeRequest]) (*connect.Response[v1.SandboxCreateNodeResponse], error)
	// Create a single edge in the configured sandbox tenant. Same gating
	// semantics as `SandboxCreateNode`.
	SandboxCreateEdge(context.Context, *connect.Request[v1.SandboxCreateEdgeRequest]) (*connect.Response[v1.SandboxCreateEdgeResponse], error)
}

// NewConsoleHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewConsoleHandler(svc ConsoleHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	consoleHealthHandler := connect.NewUnaryHandler(
		ConsoleHealthProcedure,
		svc.Health,
		connect.WithSchema(consoleHealthMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	consoleListTenantsHandler := connect.NewUnaryHandler(
		ConsoleListTenantsProcedure,
		svc.ListTenants,
		connect.WithSchema(consoleListTenantsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	consoleGetTenantHandler := connect.NewUnaryHandler(
		ConsoleGetTenantProcedure,
		svc.GetTenant,
		connect.WithSchema(consoleGetTenantMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	consoleGetSchemaHandler := connect.NewUnaryHandler(
		ConsoleGetSchemaProcedure,
		svc.GetSchema,
		connect.WithSchema(consoleGetSchemaMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	consoleQueryNodesHandler := connect.NewUnaryHandler(
		ConsoleQueryNodesProcedure,
		svc.QueryNodes,
		connect.WithSchema(consoleQueryNodesMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	consoleGetNodeHandler := connect.NewUnaryHandler(
		ConsoleGetNodeProcedure,
		svc.GetNode,
		connect.WithSchema(consoleGetNodeMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	consoleGetEdgesFromHandler := connect.NewUnaryHandler(
		ConsoleGetEdgesFromProcedure,
		svc.GetEdgesFrom,
		connect.WithSchema(consoleGetEdgesFromMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	consoleGetEdgesToHandler := connect.NewUnaryHandler(
		ConsoleGetEdgesToProcedure,
		svc.GetEdgesTo,
		connect.WithSchema(consoleGetEdgesToMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	consoleGetConnectedNodesHandler := connect.NewUnaryHandler(
		ConsoleGetConnectedNodesProcedure,
		svc.GetConnectedNodes,
		connect.WithSchema(consoleGetConnectedNodesMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	consoleSearchMailboxHandler := connect.NewUnaryHandler(
		ConsoleSearchMailboxProcedure,
		svc.SearchMailbox,
		connect.WithSchema(consoleSearchMailboxMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	consoleSandboxCreateNodeHandler := connect.NewUnaryHandler(
		ConsoleSandboxCreateNodeProcedure,
		svc.SandboxCreateNode,
		connect.WithSchema(consoleSandboxCreateNodeMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	consoleSandboxCreateEdgeHandler := connect.NewUnaryHandler(
		ConsoleSandboxCreateEdgeProcedure,
		svc.SandboxCreateEdge,
		connect.WithSchema(consoleSandboxCreateEdgeMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/entdb.console.v1.Console/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ConsoleHealthProcedure:
			consoleHealthHandler.ServeHTTP(w, r)
		case ConsoleListTenantsProcedure:
			consoleListTenantsHandler.ServeHTTP(w, r)
		case ConsoleGetTenantProcedure:
			consoleGetTenantHandler.ServeHTTP(w, r)
		case ConsoleGetSchemaProcedure:
			consoleGetSchemaHandler.ServeHTTP(w, r)
		case ConsoleQueryNodesProcedure:
			consoleQueryNodesHandler.ServeHTTP(w, r)
		case ConsoleGetNodeProcedure:
			consoleGetNodeHandler.ServeHTTP(w, r)
		case ConsoleGetEdgesFromProcedure:
			consoleGetEdgesFromHandler.ServeHTTP(w, r)
		case ConsoleGetEdgesToProcedure:
			consoleGetEdgesToHandler.ServeHTTP(w, r)
		case ConsoleGetConnectedNodesProcedure:
			consoleGetConnectedNodesHandler.ServeHTTP(w, r)
		case ConsoleSearchMailboxProcedure:
			consoleSearchMailboxHandler.ServeHTTP(w, r)
		case ConsoleSandboxCreateNodeProcedure:
			consoleSandboxCreateNodeHandler.ServeHTTP(w, r)
		case ConsoleSandboxCreateEdgeProcedure:
			consoleSandboxCreateEdgeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedConsoleHandler returns CodeUnimplemented from all methods.
type UnimplementedConsoleHandler struct{}

func (UnimplementedConsoleHandler) Health(context.Context, *connect.Request[pb.HealthRequest]) (*connect.Response[pb.HealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("entdb.console.v1.Console.Health is not implemented"))
}

func (UnimplementedConsoleHandler) ListTenants(context.Context, *connect.Request[pb.ListTenantsRequest]) (*connect.Response[pb.ListTenantsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("entdb.console.v1.Console.ListTenants is not implemented"))
}

func (UnimplementedConsoleHandler) GetTenant(context.Context, *connect.Request[pb.GetTenantRequest]) (*connect.Response[pb.GetTenantResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("entdb.console.v1.Console.GetTenant is not implemented"))
}

func (UnimplementedConsoleHandler) GetSchema(context.Context, *connect.Request[pb.GetSchemaRequest]) (*connect.Response[pb.GetSchemaResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("entdb.console.v1.Console.GetSchema is not implemented"))
}

func (UnimplementedConsoleHandler) QueryNodes(context.Context, *connect.Request[pb.QueryNodesRequest]) (*connect.Response[pb.QueryNodesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("entdb.console.v1.Console.QueryNodes is not implemented"))
}

func (UnimplementedConsoleHandler) GetNode(context.Context, *connect.Request[pb.GetNodeRequest]) (*connect.Response[pb.GetNodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("entdb.console.v1.Console.GetNode is not implemented"))
}

func (UnimplementedConsoleHandler) GetEdgesFrom(context.Context, *connect.Request[pb.GetEdgesRequest]) (*connect.Response[pb.GetEdgesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("entdb.console.v1.Console.GetEdgesFrom is not implemented"))
}

func (UnimplementedConsoleHandler) GetEdgesTo(context.Context, *connect.Request[pb.GetEdgesRequest]) (*connect.Response[pb.GetEdgesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("entdb.console.v1.Console.GetEdgesTo is not implemented"))
}

func (UnimplementedConsoleHandler) GetConnectedNodes(context.Context, *connect.Request[pb.GetConnectedNodesRequest]) (*connect.Response[pb.GetConnectedNodesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("entdb.console.v1.Console.GetConnectedNodes is not implemented"))
}

func (UnimplementedConsoleHandler) SearchMailbox(context.Context, *connect.Request[pb.SearchMailboxRequest]) (*connect.Response[pb.SearchMailboxResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("entdb.console.v1.Console.SearchMailbox is not implemented"))
}

func (UnimplementedConsoleHandler) SandboxCreateNode(context.Context, *connect.Request[v1.SandboxCreateNodeRequest]) (*connect.Response[v1.SandboxCreateNodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("entdb.console.v1.Console.SandboxCreateNode is not implemented"))
}

func (UnimplementedConsoleHandler) SandboxCreateEdge(context.Context, *connect.Request[v1.SandboxCreateEdgeRequest]) (*connect.Response[v1.SandboxCreateEdgeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("entdb.console.v1.Console.SandboxCreateEdge is not implemented"))
}
